### ISSUE TITLE
emacsclient always opens in terminal

### ISSUE THREAD

**Issue by achikin** [railwaycat/homebrew-emacsmacport#100]
I run `open /Applications/Emacs.app --args --daemon`
then `/Applications/Emacs.app/../emacsclient somefile`
and emacs opens right inside the terminal rather then in GUI
However if I open GUI version and start server inside it - everything works as expected eg. `emacsclient` open a file in GUI emacs.

**Comment by braham-snyder** [comment]
dup: https://github.com/railwaycat/homebrew-emacsmacport/issues/52
