### ISSUE TITLE
cask - (no/natural) title bar

### ISSUE THREAD

**Issue by jupl** [railwaycat/homebrew-emacsmacport#101]
I'm installing the application using cask, but modifying `mac-use-title-bar` or modifying `TransparentTitleBar` does nothing. I'm using Cask over brew due to `brew linkapps`deprecating and the README is reading like the patches are already included.

**Comment by railwaycat** [comment]
Sorry about the confusing README, no patch been applied to brew cask bundles for now. To use the patches, you have to install through `brew` and build from source code. 

I have the plan to include patches to cask and pre-built bundles in future.

**Comment by jupl** [comment]
Got it. Thanks.
