### ISSUE TITLE
Optionally remove file type icon from frame

### ISSUE THREAD

**Issue by anler** [railwaycat/homebrew-emacsmacport#104]
Hello! Do you know if there's a flag or way of removing the file type icon from the frame's title bar? (the green icon in the screenshot)

![image](https://cloud.githubusercontent.com/assets/83847/26828586/7dad1ac4-4ac2-11e7-839f-4cc53f7d50aa.png)

Thanks!

**Comment by mkhattab** [comment]
With the `--with-natural-title-bar` option, you can hide the document icon by running:

```
defaults write org.gnu.Emacs HideDocumentIcon YES
```

**Comment by anler** [comment]
Thanks a lot @mkhattab !
