### ISSUE TITLE
Equivalent for `ns-hide-emacs`? 

### ISSUE THREAD

**Issue by DarwinAwardWinner** [railwaycat/homebrew-emacsmacport#105]
Is there an equivalent to `ns-hide-emacs` in this Emacs port? The best I have so far is `(call-process "osascript" nil nil nil "-e" "tell application \"Finder\"" "-e" "set visible of process \"Emacs\" to false" "-e" "end tell")`. If there's no equivalent, can one be added?

**Comment by railwaycat** [comment]
Nope.. The AppleScript line you mentioned is also the best equivalent I found so far. 

You could contact YAMAMOTO Mitsuharu, the author of emacs Mac port by <mituharu@math.s.chiba-u.ac.jp> for the feature request.
