### ISSUE TITLE
Calling Hbc::DSL#license is deprecated

### ISSUE THREAD

**Issue by bjorntropf** [railwaycat/homebrew-emacsmacport#106]
I'm currently getting the following warning when running **brew cask install emacs-mac**

> Warning: Calling Hbc::DSL#license is deprecated!
> There is no replacement.
> /usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:19:in `block in load'

This is due to the license deprecation: https://github.com/caskroom/homebrew-cask/issues/17437

The license stanza has been initially added for #65 (e194c27).
Please note that **brew cask audit** nowadays passes without it.

Could you please remove the license stanza from all casks?

**Comment by railwaycat** [comment]
Thanks to point it out!

I've removed the license line in b01c565

**Comment by bjorntropf** [comment]
Thanks! The warnings are gone now.
