### ISSUE TITLE
Trouble installing emacs-25.3-mac-6.7

### ISSUE THREAD

**Issue by heptadecagon** [railwaycat/homebrew-emacsmacport#108]
I recently updated Homebrew, but Emacs won't upgrade. The following errors appeared:

==> Upgrading 1 outdated package, with result:
railwaycat/emacsmacport/emacs-mac emacs-25.3-mac-6.7
==> Upgrading railwaycat/emacsmacport/emacs-mac 
==> Downloading https://bitbucket.org/mituharu/emacs-mac/get/emacs-25.3-mac-6.7.
Already downloaded: /Users/Anthony/Library/Caches/Homebrew/emacs-mac-emacs-25.3-mac-6.7.tar.bz2
==> ./autogen.sh
==> ./configure --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodi
==> make
Last 15 lines from /Users/Anthony/Library/Logs/Homebrew/emacs-mac/03.make:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSWindowTabGroup.h:35:51: note: property declared here
@property (readonly, getter=isTabBarVisible) BOOL tabBarVisible;
                                                  ^
In file included from macappkit.m:37:
./macappkit.h:874:30: error: property has a previous declaration
@property (assign) NSWindow *selectedWindow;
                             ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSWindowTabGroup.h:39:28: note: property declared here
@property (weak) NSWindow *selectedWindow;
                           ^
5 errors generated.
make[1]: *** [macappkit.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [src] Error 2
make: *** Waiting for unfinished jobs....

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/railwaycat/homebrew-emacsmacport/issues

**Comment by unknownzerx** [comment]
Ditto for me.

I suppose the problem appears with Xcode 9.

**Comment by railwaycat** [comment]
Hmm.. could I get a bit more info from your side? 

The macOS version and Xcode version (looks should be 9); if `brew doctor` has any complain; and if this issue only happens when upgrade or also happens when remove it and then install from fresh.

**Comment by railwaycat** [comment]
I'm able to reproduce this issue now, not on 10.13 but on 10.12 with Xcode 9.

The strange part is if build without Homebrew formula (I mean, untar the source code, `./configure` and `make`), I won't see the build failure. Looks like some env from Homebrew affecting?

I'll continue look into this..

**Comment by heptadecagon** [comment]
I'm on 10.12.6 with Xcode 9, but I will probably upgrade to 10.13 soon. `brew doctor` did not complain.

I hope you'll understand that I'm a little reluctant to remove and then install, in case it doesn't work. I need Emacs and am not sure how I would install a previous version of a homebrew package!

In any case, I guess since you can reproduce the issue now, you don't need me to remove and install. I'm glad!

**Comment by railwaycat** [comment]
Thanks for the info. No, you don't need to do that. Please keep it if you need.

 Also you could download a pre-built binary if you like to on the latest version before I can figure out the root cause.

**Comment by heptadecagon** [comment]
Thanks! I just upgraded to 10.13 and tried again. It worked! Thanks again!

**Comment by railwaycat** [comment]
I believe this is because of a bug in emacs mac port code and Mr. Yamamoto had fix it in https://bitbucket.org/mituharu/emacs-mac/commits/b2ba54715cde5c3913f1d8072f4277e755f4e9a0

Please do a `brew update` and try again`:)`

**Comment by jupl** [comment]
Will there be an update for the Cask versions as well?

**Comment by railwaycat** [comment]
@jupl  Yes, I will do the update in about 24 hours.

**Comment by heptadecagon** [comment]
Did `brew update` on 10.13 and it still works. Thanks!
