### ISSUE TITLE
Feature request: touchbar support

### ISSUE THREAD

**Issue by idoo** [railwaycat/homebrew-emacsmacport#115]
It is possible to specify dependencies `--with-touchbar` to bind some useful commands on mac touchbar when we're using GUI mode?

**Comment by railwaycat** [comment]
Sorry for the delay on reply, I would suggest you to contact Mr Yamamoto, the developer of emacs mac port mituharu+bug-gnu-emacs-mac@math.s.chiba-u.ac.jp for feature request.
