### ISSUE TITLE
magit runs very slowly on Emacs Mac Port

### ISSUE THREAD

**Issue by debajit** [railwaycat/homebrew-emacsmacport#121]
This seems to be a known issue, and it looks like others may have found a fix: 

- https://github.com/magit/magit/issues/2909
- https://github.com/d12frosted/homebrew-emacs-plus/pull/27
- http://lists.gnu.org/archive/html/bug-gnu-emacs/2017-04/msg00201.html

Magit is heavily used by Emacs Mac users. Is this something we can fix for Emacs Mac Port as well?

**Comment by sandinmyjoints** [comment]
It looks to me like this patch was added in emacs-mac-rc2-mac-6.3 in April 2017: https://bitbucket.org/mituharu/emacs-mac/commits/df85af37ecb76855ffb9f85285e2111c612775af?at=master

**Comment by debajit** [comment]
With the latest Emacs Mac Port + the latest Magit update, it looks like this issue may be fixed. I'll update this with my findings.

**Comment by debajit** [comment]
After about a week of running the latest Emacs Mac Port (25.3.3) with the latest magit, I can confirm that magit is no longer slow (It actually runs rather very quickly). Closing this issue.
