### ISSUE TITLE
--HEAD fails

### ISSUE THREAD

**Issue by vikasrawal** [railwaycat/homebrew-emacsmacport#126]
brew install --HEAD emacs-mac

fails with the following error:

1 out of 2 hunks FAILED -- saving rejects to file mac/templates/Info.plist.in.rej
Error: Failure while executing: patch -g 0 -f -p0 -i /private/tmp/emacs-mac--patch-20180122-59873-c2moni/emacs-mac-infoplist.patch

**Comment by railwaycat** [comment]
Thanks to point it out!

Upstream accepted this patch today, I definitely need to update this formula. If you would like to make it works now, you can do `brew edit emacs-mac` and remove the `patch do-end` block from line 94 to 97.

**Comment by railwaycat** [comment]
Fixed by 164c6a8d244ff255559f08df407a7eef47cc60e3. It should works now after a `brew update`.

**Comment by vikasrawal** [comment]
Thanks. Works.
