### ISSUE TITLE
Suggestion: Have option to create and move Emacs alias to Applications

### ISSUE THREAD

**Issue by mariusk** [railwaycat/homebrew-emacsmacport#13]
First of all, thank you for supporting a very nice Emacs on OSX!

Initially when I installed Emacs with this recipe I had some issues with getting it recognized by the system as a normal app when searching for it using Cmd-Space. Typically it would only find the normal cmdline version, which doesn't work in a GUI setting of course.

Today my workflow after installing/upgrading using this recipe:
1. Create alias of Emacs in /usr/local/Cellar/emacs-mac/emacs-VERSIONETC/EmacsAlias
2. Move that EmacsAlias into /Applications
3. Rename it Emacs again inside /Applications, removing whatever old version of "Emacs" was already there

I'm probably not the only person having these issues, so if it's not too much work (haven't looked into it myself, but will consider it), maybe it would be possible to add an option to auto-install it into /Applications using the alias method, or any other method that works.

**Comment by periklis** [comment]
+1

**Comment by mariusk** [comment]
According to this http://stackoverflow.com/questions/7072208/how-do-i-create-a-macintosh-finder-alias-from-the-command-line, looks like it could be a one-liner. At the very least it should replace the note about using a symlink inside /Applications which I believe does not work (will not be found).

**Comment by mariusk** [comment]
https://github.com/railwaycat/homebrew-emacsmacport/pull/14

**Comment by railwaycat** [comment]
Thanks @mariusk, I will pick your #14 :)

**Comment by jasonm23** [comment]
Let's reopen this.

The thing is while aliases are shown in Spotlight, they're ranked extremely low.

AFAIK there's really no downside to moving the `.app` directly into `/Applications/` and then it's a first class Application, like everything else.

It seems counter-productive to me to suggest any other way of finally installing the bundle.  Does anyone have a concrete reason to not do this?

**Comment by railwaycat** [comment]
@jasonm23 Sure, I will keep this issue open for discussing.

**Comment by jasonm23** [comment]
Thank you

**Comment by jpcirrus** [comment]
The standard Homebrew method for installing application bundles is that after `brew install emacs-mac` completes then run `brew linkapps emacs-mac` which will create a symlink in `/Applications` to the `Emacs.app` bundle. The Homebrew philosophy is to keep the files of each formula in its cellar and that any required symlinks (usually just in `brew --prefix`) point to there. If the actual application bundle is required to be in `/Applications` then perhaps Homebrew isn't the correct tool and it would be better to install the binary available from the `release` page, as any custom post-install moving or copying of the original files will be sure to break other subsequent Homebrew commands such as `brew upgrade emacs-mac`, `brew remove emacs-mac`, `brew info emacs-mac`, `brew list`... as well as dependancy checking.

**Comment by jasonm23** [comment]
@jpcirrus This is nothing to do with homebrew, no, seriously.  Homebrew has it's policies because it doesn't want to touch the system...

That's fine.

This issue is about the advice given when emacs-mac is finished installing, nothing automated, just best case advice to get the best experience from OSX + Emacs.

While it's reasonable to _assume_ that moving the built osx app bundle will _break subsequent Homebrew commands..._.  It simply doesn't, you're welcome to give it a try.

Dependency checking is also unaffected by moving built osx app bundles.

And I am advocating the recommendation of `mv`ing the bundle to `/Applications`

**Comment by mariusk** [comment]
Regarding the comment about aliases being ranked low, I think ranking improves as soon as you actually select it once. The immediate downside of actually moving it into /Applications instead of using an alias is that it makes it a lot harder to test/juggle different versions around quickly (select form multiple installed versions). But I haven't actually needed this so far, so I do not think it is important.

**Comment by jasonm23** [comment]
@mariusk given that a `mv` is only going to update the volume's file index, and not actually move any files around (unless /Applications and /usr/local/Cellar are on different volumes, seems like an outer edge case to me?) then the time cost is less. (?) ... let's walk through the operation.

```
# Assuming we have a version installed and in /Applications... 
mv /Application/Emacs.app /usr/local/Cellar/emacs-mac/version-something/ # for safe keeping.
mv /usr/local/Cellar/emacs-mac/version-something-else/Emacs.app /Applications 
```
and so on... or create an alias... 

https://support.apple.com/kb/PH10609?locale=en_US ... can this be done in a Terminal, of course it can by running an overly verbose applescript, better have than snippet ready!

... I think my point is made.

**Comment by mariusk** [comment]
@jasonm23 Sure, it's not that much difference, assuming you know what you are doing. Having something stuck in one place where it can always be expected to be found (.../Cellar) and copying/aliasing into something else is always going to be slightly less risky than actually moving stuff around from one place to another. If anything goes wrong, there is always a way to clean up an retry if only the destination changes, not the source.

Having said this, we are talking about Emacs users, so I do not mean that this is a huge risk or anything, just an observation. I'm all for everything working great by default out of the box, where a "worst case" fixup is a reinstall or similar.

The way it works now is probably worse than either of the alternative solutions suggested; everything seems to install just fine, and then it simply "does not work" when trying to launch Emacs the way users typically do.

**Comment by jasonm23** [comment]
We are also talking about an edge case.  People aren't very often juggling different Emacs versions.  If they are, not only are they quite capable of deciding how they want launch / install it.

They only change that's under debate is how we advise people to get it up and running with the minimum of fuss and hassle.

There's no negative technical side effect of mv-ing the app, so it makes more sense than the shonky osascript hack.

**Comment by mariusk** [comment]
@jasonm23 Absolutely agree. Putting it in the right place in the first place would probably be the best option, when symlinking does not work and the whole alias thing look and feel very wonky.

**Comment by railwaycat** [comment]
Just a friendly reminder, I think we are discussing about the **advice** given in `brew info emacs-mac` and after installing on how to satisfy Homebrew and OS X Spotlight for App in `/Application`.

I highly not suggest to adding any operation or scripts to do anything automatically during installing.

**Comment by jasonm23** [comment]
100% agree.  No action after standard brew install should be automated.

Just an advisory note nice user experimence

**Comment by mariusk** [comment]
So assuming we're not going to make Emacs launch easily "by default" using Spotlight, we might as well mention both methods of letting Spotlight know that we've now got a proper Emacs installed. I know the one-liner I contributed is a hack (I agree), but it is arguably the less risky method since it does not touch anything else other than creating the actual alias inside `/Applications`. Moving stuff out of where `homebrew` installs it makes the assumption that `homebrew` has no direct or indirect references to it anywhere else, which may or may not be a safe assumption (no idea).

**Comment by jasonm23** [comment]
> Moving stuff out of where homebrew installs it makes the assumption that homebrew has no direct or indirect references to it anywhere else, which may or may not be a safe assumption (no idea).

Didn't I cover this already?

There are NO negative side effects from moving the generated Emacs.app.  Could we please stop rehashing the same superstition, this isn't guesswork.  It's testable.  I've thoroughly tested the scenario for a few YEARS now,  it's frustrating watching people do their terrified little cargo-cult dances.

**Comment by mariusk** [comment]
Chill @jasonm23. If your solution works just fine, we should use it and make sure that is the suggested way of making it available, and remove the advice about symlinking or other stuff that simply does not work. If it hasn't been done already that is. The problem is that when your perfect solution isn't described as such, and the suggested solution does not work, then people start reinventing workarounds. Working documented methods is a nice way to avoid it.

**Comment by jasonm23** [comment]
Yes, sorry to tip over my toys there but I just wanted to shake it up a bit to get this it resolved.

I'm happy to provide a cleanly documented method.  I think I produced a gist/script a while back, to do this and inject custom icons.

At its simplest, without modifying the bundle at all, a user could do this with Finder, however they would need to have the correct build folder.

We could display :

    open /usr/local/Cellar/emacs-mac/$latest-version/

However, this is slightly absurd, since it would be straightforward to display a shell one liner that could take care of the entire operation.

     mv /usr/local/Cellar/emacs-mac/$latest/Emacs.app /Applications/

I also think it would be helpful, to avoid a lot of support requests, if I also put a wiki based guide together. (Since I am the one who appears to feel strongly, I should do the work for this.)

I could gather up any other reference material and explain a bit about how Emacs is built and OS X app bundles in general.

**Comment by mariusk** [comment]
I vote for displaying the `mv ...` one-liner to resolve the "Emacs.app not being found by Spotlight" issue. Since Homebrew is a cmdline utility, displaying the one-liner with a brief comment on why you would typically want to do it should be sufficient.

**Comment by jasonm23** [comment]
Makes the most sense

**Comment by jasonm23** [comment]
As of Yosemite, OSX now correctly indexes symlinks in /Applications that point to bundles, so all this is now redundant and `brew linkapps` will do everything needed.

vote to close. 👍

**Comment by railwaycat** [comment]
I will close this issue because of the age. 

`brew linkapps` feature deprecated too. I can't really follow the thoughts of Homebrew recently but looks like they prefer user to install apps from cask instead of build from formula.
