### ISSUE TITLE
How to run `emacs -Q` in new frame instead of using the current frame?

### ISSUE THREAD

**Issue by lukertty** [railwaycat/homebrew-emacsmacport#130]
Just like normal `emacs -Q` do...

**Comment by railwaycat** [comment]
Sorry, could you clarify the description?

If you want to create a new frame of a running Emacs session with no customized configuration I'm afraid I don't know how to do that. And also it not related to this repo.

**Comment by railwaycat** [comment]
这个是 emacs 和 emacs-mac 两个 formula 对 `$(brew --prefix)/bin/emacs` 处理的不同。我不确定哪个偏好更合适，所以并没有做类似 emacs formula 的修改。

如果你想把它改成 emacs formula 的样子的话，简单粗暴的做法是 `unlink $(brew --prefix)/bin/emacs`，然后 `cd $(brew --prefix)/bin; ln -s $(brew --prefix)/Cellar/emacs-mac/emacs-26.1-rc1-mac-6.90/Emacs.app/Contents/MacOS/Emacs ./` （假如你安装的是最新的版本，否则需要修改一下对应的版本路径）。

比较无害一点的方法是用一个 starter，比如这个 https://gist.github.com/4043945 。把它保存到本地，换个你比较习惯的名字然后加上执行权限。

**Comment by lukertty** [comment]
嗯嗯，解决了，参考链接里的做法，旧的 

```
emacs -Q
```

相当于

```
/usr/local/opt/emacs-mac/Emacs.app/Contents/MacOS/Emacs.sh -Q
```
