### ISSUE TITLE
emacs mac port build with GnuTLS by default

### ISSUE THREAD

**Issue by railwaycat** [railwaycat/homebrew-emacsmacport#132]
and have option to build without it.

**Comment by Lokeh** [comment]
Yeah this is blocking me from using this now :( I was wondering why things were failing since I installed it on another computer last week. Is there any fix in the meantime?

**Comment by railwaycat** [comment]
https://github.com/railwaycat/homebrew-emacsmacport/commit/540104b6858bd12854266848a07df35c40f2994d
