### ISSUE TITLE
Native fullscreen?

### ISSUE THREAD

**Issue by anildigital** [railwaycat/homebrew-emacsmacport#136]
![image](https://user-images.githubusercontent.com/266/40798281-40417a1e-6528-11e8-92ac-383bef854b55.png)

Pressing that green circle button (+ icon on it when you hover) .. doesn't do fullscreen?

Is it expected behaviour currently? What do I need to get it working? 

Thanks

**Comment by railwaycat** [comment]
No, that's not expected.

Usually that green button should be a..hmm..square made by two triangles when mouse hovers. 

I believe it's from your configuration file. How about have a try to start emacs by `/Applications/Emacs.app/Contents/MacOS/Emacs -q` and see how it works?

**Comment by dpassen** [comment]
I'm seeing the same issue. And it's definitely caused by some configuration. I was able to narrow it down to [better-defaults](https://github.com/technomancy/better-defaults).

**Comment by anildigital** [comment]
This line was culprit `(if (fboundp 'menu-bar-mode) (menu-bar-mode -1))` for me.

**Comment by dpassen** [comment]
It doesn't seem like this should be effected by menu-bar-mode, though.

**Comment by megane42** [comment]
[In my environment,](In my environment,)  `(menu-bar-mode 0)` [](url)

**Comment by dpassen** [comment]
I still think it's a bug that menu-bar-mode effects the title bar.
