### ISSUE TITLE
emacs-26.1-mac-7.0 not working on apple os x 10.14

### ISSUE THREAD

**Issue by esjmb** [railwaycat/homebrew-emacsmacport#137]
Hi,

not working as above. The application opens, fails to draw screen unless one resizes. Then does not display keystrokes etc. Seems to accept keystrokes however, as Ctrl-X Ctrl-c closes. 

Does work in terminal.

Standard emacs 26.1 working fine.

**Comment by mootpointer** [comment]
I'm suffering similar issues, but I had the same problems with 25.2 as well (I upgraded to 26.1 in the hope that it would resolve issues)

**Comment by mariusk** [comment]
Made a comment related to trying a recent build here (doesn't work): https://github.com/railwaycat/homebrew-emacsmacport/issues/141#issuecomment-402458986

**Comment by mariusk** [comment]
I was able to successfully build from source and run Yamamoto's latest release on 10.14, instructions here #141 .
