### ISSUE TITLE
emacs frames don't stay on their Space 

### ISSUE THREAD

**Issue by simonmichael** [railwaycat/homebrew-emacsmacport#139]
Thanks for maintaining this emacs build. One thing is quite troublesome for me: I like to open up one or more task-specific emacs frames per Space. With other emacs builds, these frames stay put, but with emacs-mac they soon migrate to the current Space and I am constantly having to move them back. I'm not quite sure what triggers the move.

brew info emacs-mac:
railwaycat/emacsmacport/emacs-mac: stable emacs-26.1-z-mac-7.0, HEAD
YAMAMOTO Mitsuharu's Mac port of GNU Emacs
https://www.gnu.org/software/emacs/
/usr/local/Cellar/emacs-mac/HEAD-bf14aba (4,009 files, 114.9MB)
  Built from source on 2018-03-14 at 09:34:42

M-x emacs-version: 
GNU Emacs 26.0.91 (build 1, x86_64-apple-darwin16.7.0, Carbon Version 157 AppKit 1504.83) of 2018-03-14

Possibly related to #124 ?

**Comment by railwaycat** [comment]
Thanks!

I would suggest you to contact the developer of Mac port: [YAMAMOTO Mitsuharu](mailto:mituharu+bug-gnu-emacs-mac@math.s.chiba-u.ac.jp). 

BTW, the "z" in version string is just a trick to let Homebrew think this is a newer version than "rc*", please don't be confused, it's nothing different from upstream:)

**Comment by simonmichael** [comment]
Seems to happen when menu bar is disabled. Workaround: (menu-bar-mode 1).

**Comment by simonmichael** [comment]
To reproduce: (menu-bar-mode -1), cmd-h to hide emacs, switch to another desktop, cmd-tab to select emacs again: all emacs frames reappear on the current desktop.

**Comment by hisnawi** [comment]
The (menu-bar-mode- 1) did not work for me. I am on Catalina and using the latest (26.3).

**Comment by bashu** [comment]
two years later...

**Comment by railwaycat** [comment]
Frankly, I will suggest to report this issue to the developer again if you still see the problem around.
