### ISSUE TITLE
Casks are built with --without-gnutls

### ISSUE THREAD

**Issue by andrew-christianson** [railwaycat/homebrew-emacsmacport#143]
Cask apps aren't linked to libgnutls, and thus `(gnutls-available-p)` is nil.  This forces emacs to use `gnutls-cli` for TLS connections, which can be _very_ slow on some systems.

Obviously this isn't a major issue, and building from source with `brew install emacs-mac` builds with gnutls, but it would be nice, if possible, for the casks to mirror the default configuration of the formulas.

**Comment by railwaycat** [comment]
Now casks and pre-built on release page are build with gnutls and shipping with lib files in bundle.

**Comment by railwaycat** [comment]
since release https://github.com/railwaycat/homebrew-emacsmacport/releases/tag/emacs-26.1-mac-7.2

**Comment by vemv** [comment]
Hi there,

my understanding is that if I build from source (which is what `brew install emacs-mac --HEAD` does?), gnutls **won't** be used?

That appeared to be the case for me. Fresh Mojave install, `(gnutls-available-p)` returns nil and I cannnot install any packages: it will fail with `package foo is unavailable` after a ~5m wait.

**Comment by railwaycat** [comment]
Hi @vemv, sorry for the delay of reply. Now homebrew (`brew install emacs-mac`) has gnutls as required dependency.

**Comment by vemv** [comment]
Checked out, works nicely. Thanks!
