### ISSUE TITLE
latest emacs-mac won't build on High Sierra

### ISSUE THREAD

**Issue by LukeXuan** [railwaycat/homebrew-emacsmacport#147]
The latest version of emac-mac does not build on my MacOS High Sierra, with the same error reported in issue #141.

```
Last 15 lines from /Users/someone/Library/Logs/Homebrew/emacs-mac/03.make:
  CC       fontset.o
  CC       fringe.o
  CC       image.o
  CC       macappkit.o
  CC       macfont.o
  CC       terminfo.o
  CC       lastfile.o
  CCLD     temacs
Undefined symbols for architecture x86_64:
  "_IODisplayMatchDictionaries", referenced from:
      ___mac_display_copy_info_dictionary_for_cgdisplay_block_invoke in macappkit.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [temacs] Error 1
make: *** [src] Error 2
```

**Comment by railwaycat** [comment]
Hi, could you give me more information about your setup? 

Do you have Xcode beta installed and what's the output of `xcode-select -p`? What's the parameters you use when install emacs-mac by brew?

Thanks!

**Comment by LukeXuan** [comment]
I have no XCode installed and I have only command line tools.

```bash
$ xcode-select -p
/Library/Developer/CommandLineTools
```

I was building with `brew install emacs-mac --with-spacemacs-icon --with-imagemagick --with-modules --with-xml2`.

**Comment by LukeXuan** [comment]
Interestingly, building from fresh repo with
```
PATH=/usr/local/opt/texinfo/bin:$PATH ./configure --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-mac/emacs-26.1-z-mac-7.2/share/info/emacs --prefix=/usr/local/Cellar/emacs-mac/emacs-26.1-z-mac-7.2 --with-mac --enable-mac-app=/usr/local/Cellar/emacs-mac/emacs-26.1-z-mac-7.2 --with-modules --with-gnutls

MAKEFLAGS="-j8" make
```

does not encounter a single error. `brew install emacs-mac --HEAD` fails though.

**Comment by LukeXuan** [comment]
Actually, it does not build with previous release as well. It seems like something is broken with the homebrew build system, but I'm not sure where.

**Comment by railwaycat** [comment]
Yes, that's also I'm thinking...but no idea too.

**Comment by LukeXuan** [comment]
I'm going to report it upstream to Homebrew/brew.

**Comment by railwaycat** [comment]
Thanks! 

It's a rarely case that a macOS system has only command line tools but no Xcode.app. I'm not sure if Homebrew recommends use in that way.

**Comment by LukeXuan** [comment]
It turns out the choice of using "clang" or "gcc" made the difference. By invoking,

```
CC=/usr/bin/gcc HOMEBREW_NO_ENV_FILTERING=0 brew install emacs-mac
```

I haven't reported to homebrew because I'm not sure if that's their problem and they seem to have a strict rule for issue reporting.

**Comment by LukeXuan** [comment]
It turn out that the clang and gcc on my system somehow get the version 10.0, while the latest version for High Sierra should be 9.1. I reinstalled the CLI tools and it works fine now.

**Comment by etehtsea** [comment]
Same problem using:

```
~  $ clang --version
Apple LLVM version 10.0.0 (clang-1000.10.25.5)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
