### ISSUE TITLE
Cloning www.math.s.chiba-u.ac.jp hangs

### ISSUE THREAD

**Issue by drewwells** [railwaycat/homebrew-emacsmacport#15]
The git repo is hanging indefinitely. Are there any mirrors to access this repo?

**Comment by railwaycat** [comment]
No other mirrors as I know... not sure if the developer has any mirror plan. 

It took me about 10mins for first clone (US, east coast), but after that should faster...unless you clean up the homebrew cache.

**Comment by trishume** [comment]
Taking a long time (>10 minutes, hasn't finished yet) for me as well and I've heard many others complain of long download times. Perhaps we could set up a Github mirror like https://github.com/eclipse/eclipse just for nice interface and faster speed.

**Comment by railwaycat** [comment]
opened new issue to tracking repo switch #28, which would speed up the cloning and update.
