### ISSUE TITLE
Cask (26.1-z-mac-7.2) lagging behind the Formula (26.1-z-mac-7.4)

### ISSUE THREAD

**Issue by tko** [railwaycat/homebrew-emacsmacport#159]
Just wondering if the Cask is going to stay around or if we should switch to the Formula.

**Comment by ViktorHaag** [comment]
Add my vote to keeping the cask up-to-date if possible. I've run into sporadic problems rebuilding/installing emacs-mac from scratch behind my corporate firewall, and having the cask available (or a bottle) is very useful.

**Comment by railwaycat** [comment]
Hi, the cask will be there for 7.4 and future versions, sorry for the inconvenience!

I'm working on moving the build works from manual+scripts to continuous integration, but there is a delay because of some unexpected events. I can't give an exactly deadline but it should be done within one or two weeks, and before next version from upstream. 

BTW, thanks to let me know there are people need the cask version:)

**Comment by railwaycat** [comment]
Hi, sorry for the delay! Here is what I promised long ago: https://github.com/railwaycat/build-macport/releases/tag/26.1-mac-7.4

It includes the latest mac port release built (26.1-mac-7.4) and a HEAD of work branch built. I will try to make the HEAD built releases weekly if there are changes from upstream. 

As the limitation from Travis (Homebrew support and build time), I have to make the minimal support macOS version from 10.9 to 10.12. If you are still using macOS < 10.12, please feel free to let me know. I can continue to try with other CI platforms. 

These binaries are delivered directly from CI to GitHub release so currently I haven't figure out a good way to make the bundle signing automatically, I will include SHA256 sums of every zip ball in release page. 

BTW, I'm not sure which way is better, to merge build scripts and continue publish releases in this repo or have them separately? Or have a GitHub Pages? 🤔

**Comment by railwaycat** [comment]
Cask updated for emacs-26.1-mac-7.4, `emacs-mac-snapshot` and `emacs-mac-spacemacs-icon-snapshot` also been added. I know the later is not good named, any suggestion are welcome!

**Comment by ViktorHaag** [comment]
Hmmm... `brew cask info` (after updating brew) still shows the older build:
```
emacs-mac: emacs-26.1-z-mac-7.2
https://bitbucket.org/mituharu/emacs-mac.git
/usr/local/Caskroom/emacs-mac/emacs-26.1-z-mac-7.2 (64B)
From: https://github.com/railwaycat/homebrew-emacsmacport/blob/master/Casks/emacs-mac.rb
==> Name
Emacs-mac
==> Artifacts
Emacs.app (App)
/Applications/Emacs.app/Contents/MacOS/Emacs -> emacs (Binary)
/Applications/Emacs.app/Contents/MacOS/bin/ebrowse (Binary)
/Applications/Emacs.app/Contents/MacOS/bin/emacsclient (Binary)
/Applications/Emacs.app/Contents/MacOS/bin/etags (Binary)
```

**Comment by railwaycat** [comment]
@ViktorHaag Sorry, that's my fault. Should fixed after another `brew cask upgrade` or `brew update`.

**Comment by ViktorHaag** [comment]
Yep! Working now; thanks!

**Comment by railwaycat** [comment]
Hi, to reduce confusing, I merged the build scripts and CI info this repo. New release and downloads are available from release page of this repo: https://github.com/railwaycat/homebrew-emacsmacport/releases

Cask formulas updated as well.
