### ISSUE TITLE
Never load elpa packages

### ISSUE THREAD

**Issue by IsaacPhys** [railwaycat/homebrew-emacsmacport#162]
My personal configuration works well for emacs-plus. For emacs-mac, every config that depend on melpa packages fail to be loaded. So that these configs failed. e.g. My first package is exec-shell-from-path. And it gives me: error: symbols' definition is void: exec-path-from-shell-initialize.
My personal config is here.
https://github.com/IsaacPhys/Homebrewemacs

**Comment by railwaycat** [comment]
Hi @IsaacPhys, there's quite less information to see what went wrong on your emacs. 

Could you provide information of what's the way you install emacs-mac? From brew or brew cask, or download bundle from release page?

BTW, could you also verify that when you start emacs by `/Applications/Emacs.app/Contents/MacOS/Emacs.sh -q`, does `M-x list-packages` able to fetch the package lists from elpa?

**Comment by IsaacPhys** [comment]
Hi, @railwaycat I got it. My package initialization did not work. In my personal config, it only works with emacs-plus. I change the command to (package-initialize) then it is good.

**Comment by railwaycat** [comment]
Great!
