### ISSUE TITLE
emacs-mac failed to build on 10.10.2

### ISSUE THREAD

**Issue by jmeyers314** [railwaycat/homebrew-emacsmacport#17]
Gist log here: https://gist.github.com/anonymous/effe6dea2a94a3b7b217

The main error seems to be
"couldn't understand kern.osversion 14.1.0"

I tried both
`brew install emacs-mac`
and
`brew install emacs-mac -cc=gcc-4.9`
to no avail.

Any tips would be greatly appreciated!

**Comment by railwaycat** [comment]
Hi @jmeyers314, do you have a gcc or llvm/clang installed from Homebrew or other place other than the one shipping with Xcode?

**Comment by jmeyers314** [comment]
Hi @railwaycat,

The gcc-4.9 attempt should be referring to the version installed by Homebrew.  I don't think I have any non-Xcode llvm/clang.

I cleaned out my environment some more (compared to `brew doctor` in the above gist), but still run into the same error.  Is there a way I can check the compiler Homebrew is using to be certain?

Thanks.

**Comment by railwaycat** [comment]
Hmm...not see this issue before. 

So you have a gcc-4.9 installed from Homebrew and don't have other version of gcc or clang, right?

Could you give me your output of `ls -l /usr/bin/cc` ? As I know Homebrew using that one as default compiler.

**Comment by jmeyers314** [comment]
> Could you give me your output of ls -l /usr/bin/cc ? As I know Homebrew using that one as default compiler.

I get 
```
lrwxr-xr-x 1 root wheel 5 Oct 28 15:25 /usr/bin/cc -> clang
```

**Comment by railwaycat** [comment]
`/user/bin/cc` looks good...

**Comment by bru** [comment]
just wanted to say that I'm having the same issue. I tried switching compilers but still can't upgrade to the latest emacs-mac

**Comment by railwaycat** [comment]
Sorry, I will close it for now. Please feel free to reopen it or open a new issue if you see this problem again. Thanks!
