### ISSUE TITLE
Emacs 26 build error

### ISSUE THREAD

**Issue by anrddh** [railwaycat/homebrew-emacsmacport#170]
Got the following build error when trying to build emacs-app.

```
==> make
Last 15 lines from ~/Library/Logs/Homebrew/emacs-mac/03.make:
  CC       atimer.o
  CC       doprnt.o
  CC       intervals.o
  CC       textprop.o
  CC       composite.o
  CC       xml.o
  CC       lcms.o
xml.c:23:10: fatal error: 'libxml/tree.h' file not found
#include <libxml/tree.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [xml.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [src] Error 2
make: *** Waiting for unfinished jobs....
```

Any ideas?

**Comment by railwaycat** [comment]
Hi, this is the an issue of homebrew: https://github.com/Homebrew/brew/issues/5068, it's "closed" but without a fix. 

You could follow this workaround https://github.com/Homebrew/brew/issues/5068#issuecomment-429984836, or by apply this patch: https://gist.github.com/railwaycat/2bf149741d2a6e3ca1695f09289483d0. 

Honestly, I only saw this failure when I build emacs from source code (not by homebrew), usually `brew install` is able to finish without any patch or workaround. I'm not quite sure why you has this issue.

**Comment by anrddh** [comment]
The workaround worked. Thank you for the quick response.
