### ISSUE TITLE
Failed to start emacs in terminal ( fish shell ) 

### ISSUE THREAD

**Issue by huyhoang8398** [railwaycat/homebrew-emacsmacport#173]
Warning: arch-dependent data dir '/Users/travis/build/railwaycat/homebrew-emacsmacport/build-scripts/emacs-source/tmproot/libexec/emacs/26.2/x86_64-apple-darwin18.2.0/': No such file or directory
Warning: arch-independent data dir '/Users/travis/build/railwaycat/homebrew-emacsmacport/build-scripts/emacs-source/tmproot/share/emacs/26.2/etc/': No such file or directory
Warning: Lisp directory '/Users/travis/build/railwaycat/homebrew-emacsmacport/build-scripts/emacs-source/tmproot/share/emacs/26.2/lisp': No such file or directory
Error: charsets directory not found:
/Users/travis/build/railwaycat/homebrew-emacsmacport/build-scripts/emacs-source/tmproot/share/emacs/26.2/etc/charsets
Emacs will not function correctly without the character map files.
Please check your installation!

**Comment by huyhoang8398** [comment]
dupplicated 
fixed with 
```
alias emacs=/Applications/Emacs.app/Contents/MacOS/emacs
```

**Comment by cdlm** [comment]
Still it seems wrong that a build-specific path is still somewhere inside the package

**Comment by huyhoang8398** [comment]
> Still it seems wrong that a build-specific path is still somewhere inside the package
 i have to fix with alias.

**Comment by railwaycat** [comment]
Hi, could you please check that if your symbolic link is to `/Applications/Emacs.app/Contents/MacOS/Emacs` or `/Applications/Emacs.app/Contents/MacOS/Emacs.sh`?

The second is the correct one. if you are using brew cask, it should be corrected by the recent upgrade, but if you are installed by hand, you may need to fix the symbolic link by hand.

**Comment by railwaycat** [comment]
`/Applications/Emacs.app/Contents/MacOS/Emacs.sh` is also the default entrance when you open the bundle by double click.

**Comment by huyhoang8398** [comment]
```
ls -lhaF emacs
lrwxr-xr-x  1 huyhoang8398  admin    47B Jun 16 23:11 emacs@ -> /Applications/Emacs.app/Contents/MacOS/Emacs.sh
```
Yes,  i double check the symbolic link and it works fine with the newer version from brew cask now.
we dont need to make an alias anymore
