### ISSUE TITLE
Is cask preferred?

### ISSUE THREAD

**Issue by pvinis** [railwaycat/homebrew-emacsmacport#174]
Is `brew cask` the preferred way, or `brew`?

**Comment by railwaycat** [comment]
`brew cask` built tracks every release of emacs-mac-port while with `brew`, you have the option to install the latest unreleased code by `--HEAD`.

I don't have a preference between install from `brew cask` or `brew`. And currently there's no known major issue for cask which impacts user's experience. It only depends if you are comfortable with build from source code.

**Comment by pvinis** [comment]
Awesome! Thank you for explaining.
