### ISSUE TITLE
thank you railwaycat for packaging this (and thank you Mitsuharu for making it)

### ISSUE THREAD

**Issue by glyph** [railwaycat/homebrew-emacsmacport#177]
I don't have a problem.  In fact I just noticed a problem that I did have (emacs reporting "this application is not open any more" when I try to open it twice) seems to have gone away!

I just wanted to say thanks for maintaining this labor of love so I can get the best of Emacs and the best of the Mac.  I have used it every single day for years and it is hands down the best version of Emacs I've ever used, and I've used Emacs on just about every platform it supports for the last 20 years.

❤️

**Comment by railwaycat** [comment]
I will close this issue as a cleanup. I'm very glad to know you enjoy it:)
