### ISSUE TITLE
ns-use-native-fullscreen has no effect

### ISSUE THREAD

**Issue by gruntbatch** [railwaycat/homebrew-emacsmacport#181]
I realize this repository is for maintaining the homebrew cask, but I don't know of a way to submit issues directly, so feel free to remove this.

On my machine (macOS 10.13.6), `toggle-frame-fullscreen` will not use macOS's native full screen, even if `ns-use-native-fullscreen` is set to true. I can, however, enter native full screen by using the green fullscreen button or by dragging it to a new desktop.

This is in contrast to officially maintained Emacs, which automatically sets `ns-use-native-fullscreen` to true, and which enters native fullscreen when `toggle-frame-fullscreen` is called.

Building from source did not fix the problem.

Interestingly, when using the emacs-mac cask, `describe-variable` cannot detect `ns-use-native-fullscreen` as a valid variable, even though that variable is described in the source code.

**Comment by g6ai** [comment]
Can confirm this on macOS 10.14.6.

**Comment by railwaycat** [comment]
Sorry for the delay in response. If the problem still exists, you can report the issue to developer of mac port Mr. Yamamoto following this [instruction](https://github.com/railwaycat/homebrew-emacsmacport/blob/master/README.md#important-note).  The same instruction from [Emacs mac official repo](https://bitbucket.org/mituharu/emacs-mac/src/master/README-mac). 

As you have found out, this repo is only for Homebrew formula and cask, I will close this issue to make less confusing for other people.
