### ISSUE TITLE
emacs-mac is only opening in the terminal when invoked as "emacs"

### ISSUE THREAD

**Issue by theckman** [railwaycat/homebrew-emacsmacport#194]
Hi there,

I've heard good things about `emacs-mac` and wanted to give it a go, but am having some issues launching a GUI window from the terminal.

If I symlink `/usr/local/bin/emacs => /usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.9/bin/emacs` or to even `/usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.9/Emacs.app/Contents/MacOS/Emacs`, I cannot launch the GUI from the terminal invoked as `emacs` or `/usr/local/bin/emacs`.

If I invoke it as `/usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.9/Emacs.app/Contents/MacOS/Emacs` it loads the GUI Just fine. My workflow is to do some work in my editor, then invoke `nohup -- emacs -geometry 240x70 $@ 2>&1 > /dev/null &` to start a new session.

Am I missing something obvious? This seems like a difference between `emacs-mac` and `emacs-plus` and I wonder if there's a way to sort it out. I didn't see it documented anywhere, so I wasn't sure if it meant I was doing something wrong.

Cheers!
-Tim

**Comment by railwaycat** [comment]
Hi Tim,

If you symlink `/usr/local/opt/emacs-mac/Emacs.app/Contents/MacOS/Emacs.sh` to `/usr/local/bin`, it should starts the GUI for you. 

This is just different behavior, although I don't know how many users prefer to have `emacs` command start TUI or GUI.

How about an option `--with-linkapp` to let brew link `/usr/local/opt/emacs-mac/Emacs.app/Contents/MacOS/Emacs.sh` to `/usr/local/bin/emacs`?

**Comment by harritaylor** [comment]
> Hi Tim,
> 
> If you symlink `/usr/local/opt/emacs-mac/Emacs.app/Contents/MacOS/Emacs.sh` to `/usr/local/bin`, it should starts the GUI for you.
> 
> This is just different behavior, although I don't know how many users prefer to have `emacs` command start TUI or GUI.
> 
> How about an option `--with-linkapp` to let brew link `/usr/local/opt/emacs-mac/Emacs.app/Contents/MacOS/Emacs.sh` to `/usr/local/bin/emacs`?

I think that would help - I just had a similar issue.

**Comment by railwaycat** [comment]
Thanks for the feedback @harritaylor!

Unfortunately I tried and failed - Homebrew has sort of protection for "sandboxing" which prevent the formula to create a symbol link directly from Cellar to `HOMEBREW_PREFIX/bin`.

I would like to see if this starter script (or one of the improves)  fits your daily usage as `/usr/local/bin/emacs`. If it is, can I ship it as a replacement of `/usr/local/opt/emacs-mac/bin/emacs`?

https://gist.github.com/railwaycat/4043945

**Comment by railwaycat** [comment]
Or I can use the same starter as `emacs-plus` currently using:

```
#!/bin/bash
exec #{prefix}/Emacs.app/Contents/MacOS/Emacs "$@"
```

**Comment by harritaylor** [comment]
> Or I can use the same starter as `emacs-plus` currently is using:
> 
> ```
> #!/bin/bash
> exec #{prefix}/Emacs.app/Contents/MacOS/Emacs "$@"
> ```

works for me! maybe that would be useful in the `brew info` message?

**Comment by railwaycat** [comment]
> > Or I can use the same starter as `emacs-plus` currently is using:
> > ```
> > #!/bin/bash
> > exec #{prefix}/Emacs.app/Contents/MacOS/Emacs "$@"
> > ```
> 
> works for me! maybe that would be useful in the `brew info` message?

Great! I have the changes under branch https://github.com/railwaycat/homebrew-emacsmacport/tree/with-linkapp which needs a bit refine. I will merge it soon.
