### ISSUE TITLE
Key repeat is slow and choppy compared to stock Emacs builds

### ISSUE THREAD

**Issue by dandavison** [railwaycat/homebrew-emacsmacport#196]
(I'm not sure where the correct place is to report an issue with  https://bitbucket.org/mituharu/emacs-mac/src, so reporting here in case it's useful)

I was previously using this Emacs build exclusively because of the beautiful Webkit SVG support. However, I recently noticed something which has made me switch away: on my system at least, the key repeat speed is slower, and "choppier" than when using stock Emacs built straight from the main git repo. I tested with no init file, by opening a fundamental-mode buffer, creating a line of spaces, and holding down the left and right arrow keys. I checked that resource (especially CPU) usage by other applications was similar between my test runs on the two Emacsen. I tested against 27 (ed25282b82732a7370a4a55633c5830fd473a9b7) and 28 (a941a9e8c226cff8eb77c4f8d7d0d54cb4a36340) built from the main Emacs repo, and also 26.3 from Homebrew `emacs-head`: for all of those, a bar cursor moved more smoothly across the screen compared to emacs-mac, at a slightly higher speed, and without the stuttering that I see with emacs-mac.

**Comment by dotemacs** [comment]
> (I'm not sure where the correct place is to report an issue with https://bitbucket.org/mituharu/emacs-mac/src, so reporting here in case it's useful)

Not sure that the main developer of this Emacs port, Mitsuharu Yamamoto, reads this repo and its issues, so it might be an idea to contact them via email, which can be obtained here: https://github.com/railwaycat/homebrew-emacsmacport/issues/52#issuecomment-356072894

**Comment by dandavison** [comment]
Thanks. Hm, after reinstalling, I cannot reproduce what I was claiming. Closing this.

**Comment by sandinmyjoints** [comment]
I have experienced this as well. I always assumed it was due to some package I was using, but your report makes me think not.

**Comment by dandavison** [comment]
I'll carry on watching out for it. Let's re-open this and contact the author if any of us can come up with instructions for reproducing it predictably.
