### ISSUE TITLE
Emacs 27 support

### ISSUE THREAD

**Issue by abbaswasim** [railwaycat/homebrew-emacsmacport#197]
Sorry for being brief, more of a question than an issue. Is there any plan to support/port Emacs 27?

**Comment by railwaycat** [comment]
Hi @abbaswasim, you can install emacs 27 by `--HEAD` option from brew (not cask), which is based on the 27.0.91 version, the first (also the latest) pretest release of 27. 

The work branch of <https://bitbucket.org/mituharu/emacs-mac/> now aligns to emacs 27, I don't know the reason why Mr. Yamamoto, the developer of emacs mac port, didn't release pretest version as usual. I will keep tracking and update the formula if any emacs-mac 27 pretest or release comes out.
