### ISSUE TITLE
Trashed files cannot be recovered by "put back" in the right-click menu

### ISSUE THREAD

**Issue by ywwry66** [railwaycat/homebrew-emacsmacport#199]
If I use `move-file-to-trash` to trash a file/folder, the trashed file cannot be recovered by Finder. Either there is no "put back" option in the right-click menu, or the "put back" option exists but does not work.

I am using macOS 10.15.4, and emacs version is emacs-26.3-z-mac-7.9.

**Comment by ywwry66** [comment]
Well, I just figured I should report this to mituharu+bug-gnu-emacs-mac@math.s.chiba-u.ac.jp. But is there anyone else who can confirm this bug?

**Comment by rbutoi** [comment]
Just tested, there is indeed no "put back" option but you can just drag the file out of the trash. Perhaps Emacs doesn't set where "back" is. I also made the same mistake in https://github.com/railwaycat/homebrew-emacsmacport/issues/198, I'll need to email upstream.

**Comment by ywwry66** [comment]
Thanks for testing!

**Comment by ywwry66** [comment]
Closing because this is not a bug of this homebrew cask.

**Comment by ywwry66** [comment]
Just to clarify, this is not a bug. `mac-system-move-file-to-trash-use-finder` is the variable
 that controls this.
