### ISSUE TITLE
Focus jumps to another fullscreen frame when showing completions window

### ISSUE THREAD

**Issue by rurbina** [railwaycat/homebrew-emacsmacport#200]
Focus jumps to another fullscreen frame when showing a large `*Completions*` window.

I launch emacs, and make the first frame fullscreen. I open a second frame, it launches fullscreen as well. There I open a file on that second frame, and I use a tramp path using `/scp:user@host:/path/to`. Pressing tab autocompletes the only matching path. I reach a point where `.../some/path/to/te` matches about 180 files all beginning with the same word, _template_. I usually tab tab tab until it doesn't match and shows a `*Completions*` buffer. But when this happens, my focus switches to the first frame. I then have to `C-x 5 o` to return to the frame with the active minibuffer and completions list.

I think this is a bug. I can replicate it consistently. I'm using a blank `.emacs` file and it happens anyways. _Find file_ is the one I can replicate the easiest, but it happens with several commands requiring a completions buffer. It only happens in fullscreen, using windowed frames does not show this buggy behavior.

I'm on macOS High Sierra. I built the port with `brew install emacs-mac --with-{natural-title-bar,modern-icon,imagemagick}`, but this also happens with the binary package.

I always use the EmacsForMacOSX.com binary and it never does that. I downloaded the current version (26.3 built on 2019-09-02) and it works fine.

I want to use this port because I need ImageMagick support. I can provide any logs or traces or whatever.

Thank you.

**Comment by railwaycat** [comment]
Hi @rurbina, this not looks like a bug related to packing and homebrew formula, sorry I have to forward you to the developer of emacs mac port: Mr Yamamoto. As he mentioned in the readme file, you can report bug by sending email to <mituharu+bug-gnu-emacs-mac@math.s.chiba-u.ac.jp>

**Comment by rurbina** [comment]
Yes, I don't think it's because of the formula, you're right. Thank you!

**Comment by deftsp** [comment]
I fix it by using hammpersoon to focus the last focus frame.

**Comment by rurbina** [comment]
Good to know it's not just me! I'll try that, thanks!

**Comment by noctuid** [comment]
@deftsp Could you post your solution?

**Comment by deftsp** [comment]
@noctuid I got a better solution without  hammerspoon

on macOS, when multi frames,  if switch back to emacs, the focus frame may not be the one when leaving. 

Using the following code to fix the bug, it just save then frame when emacs deactivated and restore it when get focus.

@rurbina, I think maintain a  frame stack with the help of `focus-in-hook ` and `focus-out-hook`  can slove it.

```
(defvar tl/emacs-deactivated-focus-frame nil
  "The frame when emacs lost focus.")

(defun tl/on-emacs-deactivated ()
  (setq tl/emacs-deactivated-focus-frame (selected-frame)))

(add-hook 'focus-out-hook 'tl/on-emacs-deactivated)

(defun tl/on-emacs-activated ()
  (when (and tl/emacs-deactivated-focus-frame
             (not (eq (selected-frame) tl/emacs-deactivated-focus-frame)))
    (select-frame-set-input-focus tl/emacs-deactivated-focus-frame)
    (setq tl/emacs-deactivated-focus-frame nil)))

(add-hook 'focus-in-hook 'tl/on-emacs-activated)
```

**Comment by jdtsmith** [comment]
@rurbina did you ever hear back from the emacs-mac maintainer on this issue?  This makes tramp (and magit) very painful with multiple frames.  I tried @deftsp's solution but it causes problem with frames on multiple spaces (switching space flings you back!).

**Comment by rurbina** [comment]
@jdtsmith no, I never heard back. And I didn't keep trying, I'm sorry, but it was simply way too annoying. All I wanted was inline image resizing, which required ImageMagick, and Emacs 27 can resize without IM, and the EmacsForMacOSX.com version works fine for me.

**Comment by deftsp** [comment]
@jdtsmith  This is my updated solution. I have only tested it with Emacs28.
https://github.com/deftsp/.emacs.d/blob/a2e295783018c2dcb5130986001649d99c5a5563/lisp/03frame.el#L37

**Comment by jdtsmith** [comment]
Thanks @deftsp.  I tested that out, but it interferes with native tabs.  This is easily seen by invoking the "tab picker" using `mac-toggle-tab-group-overview`, and selecting another frame/tab.  Your delayed check switches you back to the original frame (emacs-mac 27.1).  

If the random-frame/space-switch issue were fixed, and with a few other tweaks (leave tabs displayed in fullscreen, add a "New Window" command to the dock icon) emacs-mac would truly shine!

**Comment by jdtsmith** [comment]
Thanks @deftsp.  I tested that out, but it interferes with native tabs.  This is easily seen by invoking the "tab picker" using `mac-toggle-tab-group-overview`, and selecting another frame/tab.  Your delayed check switches you back to the original frame (emacs-mac 27.1).  

Have you found a simple reproducible set of steps that can generate the "frame/space" jumping bug?  If we can create such a minimal example it's possible the developer could investigate.

**Comment by jdtsmith** [comment]
For anyone following along here, I have been in touch with the emacs-mac maintainer, and he has identified and fixed the bug leading to this "random frame switching" behavior.  It turns out it has nothing to do with external processes, as used by e.g. magit or tramp, but to _long-running_ commands.  You can evaluate `(while t)` in the scratch buffer and get the same space & tab auto-switching behavior.  

The issue was drawing the "circle spinner" at top right of the menu bar, to show Emacs is busy.  This was being done on _all_ frames, causing MacOS to auto-switch.  The fix was simple, and should come out soon.

**Comment by jdtsmith** [comment]
The latest release `27.2-mac-8.2` includes a fix for this behavior, which was caused by long running processes (like tramp or magit) placing an _hourglass_ on the window frame, giving it focus and causing the space jumps, etc.
