### ISSUE TITLE
Runtime failure on OS X 10.15.4

### ISSUE THREAD

**Issue by stefanoric** [railwaycat/homebrew-emacsmacport#201]
Hi,

I just installed on Mac OS 10.15.4 but when I run it from the command line I get this error:

```
dyld: Library not loaded: /usr/local/opt/libffi/lib/libffi.6.dylib
  Referenced from: /usr/local/opt/glib/lib/libgobject-2.0.0.dylib
  Reason: image not found
```

**Comment by railwaycat** [comment]
Could you let me know your installation is by `brew install` or `brew cask install`?

Thanks!

**Comment by railwaycat** [comment]
I will close this issue for now and please feel free to reopen it or open new one if same issue occurs.
