### ISSUE TITLE
Inclusion of a patch for multi-tty access

### ISSUE THREAD

**Issue by rougier** [railwaycat/homebrew-emacsmacport#202]
From this [blog post](https://ylluminarious.github.io/2019/05/23/how-to-fix-the-emacs-mac-port-for-multi-tty-access/), there is a fix for the multi-tty problem for emacs-mac. Would that be possible to include the two patches proposed by  George P. II ?

See also the [pending PR](https://bitbucket.org/mituharu/emacs-mac/pull-requests/2/add-multi-tty-support-to-be-on-par-with/diff) at Mitsuharu Yamamoto repository.

**Comment by railwaycat** [comment]
Yes, I'm watching the pending PR for a while. Thanks for the suggestion! It worth a try. I will make the update.

**Comment by railwaycat** [comment]
reopen it for issue tracking.

**Comment by railwaycat** [comment]
patch is on by 098ed31158c8dd3d292fff004b140a41d8d636d8
