### ISSUE TITLE
Emacs compile with modules for vterm? 

### ISSUE THREAD

**Issue by SreenivasVRao** [railwaycat/homebrew-emacsmacport#204]
Hi, looks like this wasn't compiled with modules - I get an error when I try to run vterm. Any ideas?

**Comment by railwaycat** [comment]
They are compiled. It is possible that modules won't work if cask emacs with signature, I'm looking at the problem and hope I could ship a new cask build with a fix.

**Comment by railwaycat** [comment]
Hi @SreenivasVRao, could you please confirm that the error you saw when enable vterm is the message similar to below?

```
not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
```

**Comment by SreenivasVRao** [comment]
Hi @railwaycat thanks for the quick reply. I made a mistake when I was installing this via brew.

I only had to do: brew --with-modules install emacs-mac 

So this seems unrelated to the signature issue.

**Comment by railwaycat** [comment]
Glad to hear that:) So you installed from `brew` not `brew cask`. Build from `brew` should be good, the `--with-modules` option was there for a while.

`brew cask` build still has an issue relate to bundle signature, which I mentioned above.

**Comment by fpatz** [comment]
Hi @railwaycat, I had this problem with a previous build, and it went away after ```brew cask upgrade emacs-mac```. Out of interest: can you point me to the change that fixed this? I can't find it in the commit history ...
