### ISSUE TITLE
Hardcoded charsets directory breaks command-line binaries

### ISSUE THREAD

**Issue by Benaiah** [railwaycat/homebrew-emacsmacport#21]
I like to use Emacs on the command line as well as graphically, and I've done so in the past by symlinking the `Emacs.app/Contents/MacOS/bin/*` binaries to `~/bin` (which is on my path). Unfortunately, though the graphical version of Emac still works fine, the binaries in that bin directory fail with the following error:

```
Warning: arch-dependent data dir `/Users/xin/emacs-mac-build/libexec/emacs/24.5/x86_64-apple-darwin13.4.0/': No such file or directory
Warning: arch-independent data dir `/Users/xin/emacs-mac-build/share/emacs/24.5/etc/': No such file or directory
Warning: Lisp directory `/Users/xin/emacs-mac-build/share/emacs/24.5/lisp': No such file or directory
Error: charsets directory not found:
/Users/xin/emacs-mac-build/share/emacs/24.5/etc/charsets
Emacs will not function correctly without the character map files.
Please check your installation!
```

It appears that the charsets directory has been hardcoded to a specific location on the computer that built the binary, a location that obviously does not exist normally. This is preventing the command-line emacs from launching.

This is also important because, as far as I know, the binaries in `bin` are the only way to call `emacs --debug-init` to debug initialization scripts, something I have to do quite often.

**Comment by Benaiah** [comment]
In the latest version, the error message has changed to the following:

````
Warning: arch-dependent data dir `/Users/build/emacs-mac-build/libexec/emacs/24.5/x86_64-apple-darwin13.4.0/': No such file or directory
Warning: arch-independent data dir `/Users/build/emacs-mac-build/share/emacs/24.5/etc/': No such file or directory
Warning: Lisp directory `/Users/build/emacs-mac-build/share/emacs/24.5/lisp': No such file or directory
Error: charsets directory not found:
/Users/build/emacs-mac-build/share/emacs/24.5/etc/charsets
Emacs will not function correctly without the character map files.
Please check your installation!
````

**Comment by Benaiah** [comment]
Uninstalling the `brew cask` version and installing the `brew` version fixed the issue.

**Comment by cap10morgan** [comment]
I would still like to see this get fixed.

**Comment by sgsharma** [comment]
Were there any updates on this issue?

**Comment by xor-xor** [comment]
@sgsharma - I don't think so, I still get this error on 26.1:
```
Warning: arch-dependent data dir '/Users/build/emacs-mac-build/libexec/emacs/26.1/x86_64-apple-darwin13.4.0/': No such file or directory
Warning: arch-independent data dir '/Users/build/emacs-mac-build/share/emacs/26.1/etc/': No such file or directory
Warning: Lisp directory '/Users/build/emacs-mac-build/share/emacs/26.1/lisp': No such file or directory
Error: charsets directory not found:
/Users/build/emacs-mac-build/share/emacs/26.1/etc/charsets
Emacs will not function correctly without the character map files.
Please check your installation!
```

**Comment by zijianyue** [comment]
me too , macos 10.13.6 High Sierra
installed from “brew cask install emacs-mac”

**Comment by leohzhuang** [comment]
Hi, @railwaycat , were there any updates on this issue?

**Comment by keldonin** [comment]
Same problem to me.

**Comment by railwaycat** [comment]
sorry, I'm working on a patch for upstream but may not able to finish it in the next 2-3 days. 

Meanwhile the workaround is re-install from brew instead of brew cask, or use `alias emacs=/Applications/Emacs.app/Contents/MacOS/emacs`.

**Comment by railwaycat** [comment]
I fixed it :)

A pull request submitted to upstream for the self-contained build and starter script patch. Meanwhile before new release, I included this patch in an unofficial "release" for cask and pre-built bundle users. 

Please upgrade your cask or download from the release page: https://github.com/railwaycat/homebrew-emacsmacport/releases/tag/emacs-26.2-mac-7.6.1
