### ISSUE TITLE
have all icons inside this repo

### ISSUE THREAD

**Issue by railwaycat** [railwaycat/homebrew-emacsmacport#211]
to avoid another issue like #208

**Comment by sleepyfran** [comment]
On a similar note (I don't know if this is already available and I'm just missing it) it'd be wonderful to have the Big Sur icon integrated as well:
https://github.com/nobu417/emacs-icon-replacement-for-macos-big-sur

**Comment by railwaycat** [comment]
Thanks! Good suggestion:)

**Comment by railwaycat** [comment]
I added the option for this icon first: https://github.com/railwaycat/homebrew-emacsmacport/commit/96172418a421118b707d3d9f25a11c441d037cce

**Comment by railwaycat** [comment]
A list of icon and their author, along with install options added to wiki: https://github.com/railwaycat/homebrew-emacsmacport/wiki/Icons
