### ISSUE TITLE
`upgrade' error from emacs-26.3-z-mac-7.8 -> emacs-26.3-z-mac-7.9 --with-natural-title-bar

### ISSUE THREAD

**Issue by srustamo** [railwaycat/homebrew-emacsmacport#214]
os x 10.13.6 (17G14019)
```
==> Patching
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/srmbp2/Library/Caches/Homebrew/downloads/481db406a9f064d618913d52172ad647765ab84ff8131278e725a4e223303610--emacs-mac-title-bar-7.4.patch
```

**Comment by secworks** [comment]
I see the same issue when trying to install emacs 27.1.

macOS Catalina 10.15.6.
Updated homebrew 2020-08-12, 18:00 CET and ran "brew upgrade emacs-mac".

==> Installing railwaycat/emacsmacport/emacs-mac --with-natural-title-bar --with-modern-icon
==> Patching
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/js/Library/Caches/Homebrew/downloads/481db406a9f064d618913d52172ad647765ab84ff8131278e725a4e223303610--emacs-mac-title-bar-7.4.patch

**Comment by srustamo** [comment]
For what it's worth, I ended up uninstalling with `brew uninstall` and reinstalling. Worked.

**Comment by secworks** [comment]
I also did brew uninstall, but got the same issue with the patch for title-bar. I know run Emacs without the title-bar option. It is no biggie.

**Comment by railwaycat** [comment]
I can reproduce this issue by the following steps:

1. remove current installed `brew remove emacs-mac`
2. checkout an older version
```
cd `brew --prefix`/Homebrew/Library/Taps/railwaycat/homebrew-emacsmacport
git checkout emacs-26.3-mac-7.9
```
3. install emacs-mac with a patch
```
HOMEBREW_NO_AUTO_UPDATE=1 brew install emacs-mac --with-natural-title-bar
```
4. `brew cleanup`
5. `brew update && brew upgrade`

I'm not sure it's an issue of my formula, or an issue on Homebrew side when upgrade with patch.

**Comment by railwaycat** [comment]
close the issue for now as we have a workaround.

**Comment by railwaycat** [comment]
Removed the workaround, looks they no longer needed. I found that when moving patches to another directory.
