### ISSUE TITLE
Emacs 27

### ISSUE THREAD

**Issue by TimWSpence** [railwaycat/homebrew-emacsmacport#216]
Are there plans to upgrade to emacs 27 now that it's been released? 🙂

**Comment by TimWSpence** [comment]
Actually, having looked at https://bitbucket.org/mituharu/emacs-mac/src/master/ I see you're already working on it :) Thank you!!! I guess I would change the question to: is there an ETA?

**Comment by railwaycat** [comment]
Hi @TimWSpence, have to clarify that I'm not the developer of Emacs Mac port, but just own this Homebrew formula and cask builds.

I did update the brew formula and casks are on the way. If you install Emacs-mac by `brew install` you should see the update now; the casks will available in hours. 
Thanks for the remind:)

**Comment by hmelman** [comment]
I'm trying the release build for 10.14 (on 10.15 if it matters) and don't see the new json functions like  `json-serialize` and `json-insert`

**Comment by hmelman** [comment]
I'm trying the release build for 10.14 (on 10.15 if it matters) and don't see the new json functions like  `json-serialize` and `json-insert`

**Comment by TimWSpence** [comment]
Thanks @railwaycat I probably should have noticed that! 😂

**Comment by railwaycat** [comment]
@hmelman That's my fault, the CI is using the old build scripts. I will release a update this weekend includes json support and also `--with-json` option for brew formula.

**Comment by railwaycat** [comment]
Both brew formula and brew cask updated with json support. 

For brew formula, json support is on by default. For people don't want this feature, they will need to explicitly specify `--without-json`. More discussing in #219 

For brew cask, a "cask/prebuilt only" release was out as emacs-27.1-mac-8.0.1, which includes the native json support. `brew upgrade` should able to pick up this update. More info on release page: https://github.com/railwaycat/homebrew-emacsmacport/releases/tag/emacs-27.1-mac-8.0.1
