### ISSUE TITLE
Headless Emacs 27.1 daemon server segment fault when use emacsclient to connect to it

### ISSUE THREAD

**Issue by lululau** [railwaycat/homebrew-emacsmacport#218]
1. Start a headless emacs server: `emacs --daemon=test`
2. Connect to the server: `emacsclient -t -s test my-file.txt`

The server throws segment fault, and exit abnormally.

Installation options: `brew install emacs-mac  --with-natural-title-bar --with-spacemacs-icon`

**Comment by railwaycat** [comment]
I can reproduce this issue on my side, even with the multi-tty patch.

**Comment by lkzz** [comment]
me too!

**Comment by qyin** [comment]
Same here. It works fine with 26.3. 

When I upgrade emacs to 27.1, it reports server segment fault as mentioned above.

**Comment by railwaycat** [comment]
unfortunately I'm able to reproduce this issue with vanilla build Emacs-mac. Sorry for the redirecting but I would suggest to report this issue to the developer Mr. Yamamoto <mituharu+bug-gnu-emacs-mac@math.s.chiba-u.ac.jp>

More about bug reporting are here: https://bitbucket.org/mituharu/emacs-mac/src/master/README-mac

**Comment by railwaycat** [comment]
I saw a commit on Emacs-mac which looks fixed this issue: https://bitbucket.org/mituharu/emacs-mac/commits/c89409f46330e5922ebcc5696ddea5eaba884f38

I haven't try it, but `brew install emacs-mac --HEAD` should able to pick up this change.

**Comment by lululau** [comment]
This issue should have been fixed
