### ISSUE TITLE
brew failed to fetch emacs-mac

### ISSUE THREAD

**Issue by Skyfold** [railwaycat/homebrew-emacsmacport#22]
I'm not sure is this is a brew problem or emacs-mac repo problem, but it looks like something changed without the build being updated. I'm on OS X 10.9.5. (Note this is after brew update and brew doctor)

❯ brew install emacs-mac                                                                                                                     
==> Installing emacs-mac from railwaycat/homebrew-emacsmacport
==> Cloning http://www.math.s.chiba-u.ac.jp/~mituharu/emacs-mac.git
Updating /Library/Caches/Homebrew/emacs-mac--git
warning: requested range invalid; we may already have all the data.
warning: requested range invalid; we may already have all the data.
error: Unable to find d6697c27f9aadfb421dc9e126c70175d4e3f38ec under http://www.math.s.chiba-u.ac.jp/~mituharu/emacs-mac.git
Cannot obtain needed commit d6697c27f9aadfb421dc9e126c70175d4e3f38ec
while processing commit 8272c1dbe96b14930a91807dce7a2a67c09fff4d.
error: Fetch failed.
Error: Failed to download resource "emacs-mac"
Failure while executing: git fetch -q origin

**Comment by deprecated** [comment]
I get similar errors when trying to upgrade emacs-mac from homebrew. For instance, last night I got:
```
==> Installing emacs-mac
==> Cloning http://www.math.s.chiba-u.ac.jp/~mituharu/emacs-mac.git
Updating /Library/Caches/Homebrew/emacs-mac--git
error: Unable to get pack index http://www.math.s.chiba-u.ac.jp/~mituharu/emacs-mac.git/objects/pack/pack-c3a8f23a98140df3eed0deeefe89a031c97e0eae.idx
error: Unable to find 5e73e0d9acdfa6bde25ee2e9c3244d2a8dda858a under http://www.math.s.chiba-u.ac.jp/~mituharu/emacs-mac.git
Cannot obtain needed blob 5e73e0d9acdfa6bde25ee2e9c3244d2a8dda858a
while processing commit 866501efe0fdc0c29448e0aaf8696eb0a3c8fcd6.
error: fetch failed.
Error: Failed to download resource "emacs-mac"
Failure while executing: git fetch -q origin
```

But the exact error is not repeatable. Today I get:
```
[ ... ]
error: Unable to find 5fdc612745165110dff7d17c4c1eab8bb68e36aa under http://www.math.s.chiba-u.ac.jp/~mituharu/emacs-mac.git
Cannot obtain needed commit 5fdc612745165110dff7d17c4c1eab8bb68e36aa
while processing commit 866501efe0fdc0c29448e0aaf8696eb0a3c8fcd6.
[ ... ]
``` 

From brief googling it looks like this might be a server configuration issue.  Perhaps it could be solved by running `git gc` on the server and/or updating to a newer version of git.

**Comment by stormpat** [comment]
+1

**Comment by hollingberry** [comment]
If you can't install the formula with `brew install emacs-mac`, try using [Homebrew Cask](http://caskroom.io) to install the cask with `brew cask install emacs-mac`.

Worked for me.

**Comment by railwaycat** [comment]
opened new issue to tracking repo switch #28, which would speed up the cloning and update.

**Comment by vimniky** [comment]
I'm using spacemacs , and I have this problem too when I use racket-mode .  I can figure out what's going on .

**Comment by jbrown419** [comment]
fatal: unable to access 'https://github.com/Homebrew/brew/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
is the download url valid?

Failed during: git fetch origin master:refs/remotes/origin/master --tags --force
Johns-Mac-mini:~ johnbrown$ ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
curl: (22) The requested URL returned error: 400
