### ISSUE TITLE
Bundle libjasson

### ISSUE THREAD

**Issue by ksqsf** [railwaycat/homebrew-emacsmacport#220]
libjasson seems not bundled with emacs itself, but linked dynamically.

```
(fboundp 'json-parse-string) => nil
```

It would be nice if this formula & cask can have libjasson enabled.

**Comment by pkryger** [comment]
Won't this be fixed with #219?

**Comment by msanders** [comment]
I would be interested in seeing this included in the cask as well.

**Comment by railwaycat** [comment]
Both brew formula and brew cask has the native json support update now. 

You can see more discussing in #219 and #216
