### ISSUE TITLE
brew install fails because of gist.github.com

### ISSUE THREAD

**Issue by nipuna-perera** [railwaycat/homebrew-emacsmacport#222]
I am trying to install latest emacs-mac behind my company firewall. gist.github.com is blocked by my company. Could the following file be moved to somewhere else?

https://gist.github.com/lululau/f2e6314a14cc95586721272dd85a7c51/raw/f5a92d3e654cc41d0eab2b229a98ed63da82ee1c/emacs-mac-title-bar-7.4.patch

```
==> Downloading https://gist.github.com/lululau/f2e6314a14cc95586721272dd85a7c51/raw/f5a92d3e654cc41d0eab2b229a98ed63da82ee1c/emacs-mac-title-bar-7.4.patch

curl: (22) The requested URL returned error: 403
Error: Failed to download resource "emacs-mac--natural-title-bar-patch"
```

@lululau @railwaycat

**Comment by railwaycat** [comment]
Thanks to let me know! Let me see..

**Comment by railwaycat** [comment]
Hi @nipuna-perera, could you let me know if hostname `gist.githubusercontent.com` get blocked too?

**Comment by nipuna-perera** [comment]
Yes, anything to do with "gist" gets blocked. however, `ttps://raw.githubusercontent.com/` works. Most of the brew taps use that.
