### ISSUE TITLE
\usr\local\share\emacs\site-lisp not in the cask version emacs load-path

### ISSUE THREAD

**Issue by ywwry66** [railwaycat/homebrew-emacsmacport#225]
Hi, as described in the title, when using `brew cask install emacs-mac`, \usr\local\share\emacs\site-lisp is not in `load-path`.

If I use `brew install emacs-mac` instead, it is in `load-path` because of https://github.com/railwaycat/homebrew-emacsmacport/blob/e4df6a9b83f113770c5ac70723d6798a4c8a9cdf/Formula/emacs-mac.rb#L130 I believe.

Could you add that to the cask as well so that emacs works better with other homebrew packages (maxima for example)?

**Comment by railwaycat** [comment]
No problem! I will have it fixed in the next cask release. 

However I cannot include a variable in the bundle, so I will have to hardcode both `/usr/local/share/emacs/site-lisp` and `/opt/homebrew/share/emacs/site-lisp` in the `load-path`, the later is for homebrew on Apple Silicon.

**Comment by ywwry66** [comment]
Are you able to bundle `subdirs.el` in those directories (just symlink to `/usr/local/opt/emacs-mac/emacs-27.1-mac-8.1/share/emacs/site-lisp/subdirs.el`)? Because Emacs won't search into subdirectories unless that file is present.

**Comment by railwaycat** [comment]
I think it's possible. Let me see..

**Comment by railwaycat** [comment]
Hi, I made a change to place `subdirs.el` under the `$(brew --prefix)/share/emacs/site-lisp/` directory. That change is in cask formulas so it won't need a new build, you can see it for a *reinstall* or remove it and install again.

**Comment by ywwry66** [comment]
Thanks! Look forward to the next cask release.
