### ISSUE TITLE
Enable OS X keyboard shortcuts

### ISSUE THREAD

**Issue by cddesja** [railwaycat/homebrew-emacsmacport#229]
I am sure there's a way to do this, but I'm reasonably new to Emacs and just started using this package, but I am wondering how to enable the OS X keyboard shortcuts (like command + c, command + v, and so on). I understand this isn't really a bug, but could this be added to the wiki?

**Comment by railwaycat** [comment]
I hope this gist and its discussion would help you. https://gist.github.com/railwaycat/3498096

Thanks for the suggestion, those information should have a page in the wiki.
