### ISSUE TITLE
cask build for Apple Silicon

### ISSUE THREAD

**Issue by railwaycat** [railwaycat/homebrew-emacsmacport#230]
I tried to make a cross-platform build but failed, more exactly on cross-platform here: build an arm64 + x86_64 universal binary on x86_64 platform. 

Error happens on linking of `temacs`, `etags` and `emacsclient`, I'm suspecting if I didn't set correct parameters for `configure`. But even if I get binary of temacs successfully, the compiling of elisp code will definitely fail, because the `temacs` got from cross-compiling will not able to run on host machine for elisp code. 

I tried another path, make a x86_64 bundle first, then use `lipo` to stitch arm64 binary into it. It succeed partly: the bundle after surgery runs on M1 machine and be recognized as "Apple" arch, but the same bundle refuses to start on x86 machine, I'm still finding the reason.

**Comment by railwaycat** [comment]
My summary for now:

1. There are a blocker on build a universal Emacs bundle satisfies both arm64-apple and x86_64-apple platforms.
2. As my knowledge for now, I have to use an M1 machine to build arm64 bundle of Emacs.

So sadly there might no arm64 cask bundle available in a short time. I'm waiting for the AWS M1 instance available or the virtualization solution on running macOS on M1 available -- any of them comes first.

**Comment by sleepyfran** [comment]
I'm getting this error when trying to compile on my M1 MBA:
```
Last 15 lines from /Users/sleepyfran/Library/Logs/Homebrew/emacs-mac/03.make:
  CC       json.o
  CC       macappkit.o
  CC       macfont.o
  CC       terminfo.o
  CC       lastfile.o
  CCLD     temacs
codesign -s - -f temacs.tmp
temacs.tmp: replacing existing signature
../build-aux/install-sh -c -d ../etc
/Library/Developer/CommandLineTools/usr/bin/make -C ../lisp update-subdirs
cp -f temacs bootstrap-emacs
rm -f bootstrap-emacs.pdmp
./temacs --batch  -l loadup --temacs=pbootstrap
make[1]: *** [bootstrap-emacs.pdmp] Killed: 9
make: *** [src] Error 2
```

Is there any way to get more debug data or do you know what might be happening?

**Comment by railwaycat** [comment]
@sleepyfran sorry I didn't see this error before. Would you like to have another try after `brew cleanup` and `brew update`?

If the failure still exists, It will be great if you could post the output of `brew doctor` and `brew config` here, thanks!

**Comment by sleepyfran** [comment]
@railwaycat tried again after running the commands you told me and I got the same result. This is the output of doctor and config:
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  gnupg
```
```
HOMEBREW_VERSION: 2.7.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: cd191a7f6c4c8e053336d0ea34a9886b12d06470
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3b97338fc01697a1965b5cc3124ca28ad8d82335
Core tap last commit: 12 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.30.0 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 15.0.1
macOS: 11.1-arm64
CLT: 12.3.0.0.1.1607026830
Xcode: 12.4
Rosetta 2: false
```

**Comment by sleepyfran** [comment]
Just found this issue on the `emacs-plus` repo that seems like the same issue as mine: https://github.com/d12frosted/homebrew-emacs-plus/issues/292

I'm trying to compile v28 as they suggest, will report back :)

**Comment by railwaycat** [comment]
Thanks for the update! Now I can see the difference in `src/Makefile.in` between the upstream changes and the current code sign patch this repo using.

In theory `brew install --formula emacs-mac` or `brew install --formula emacs-mac --head`, one of them should pass the building without error (because they are using different patches). But not sure for what reason I can't reproduce this error, on both.

**Comment by railwaycat** [comment]
Not sure if #237 could gives your some help @sleepyfran.

**Comment by HIRANO-Satoshi** [comment]
`brew install --formula emacs-mac` works and Emacs runs greatly.  

Thanks @railwaycat , @sleepyfran

**Comment by jmhammond** [comment]
> I'm getting this error when trying to compile on my M1 MBA:
> 
> ```
> Last 15 lines from /Users/sleepyfran/Library/Logs/Homebrew/emacs-mac/03.make:
>   CC       json.o
>   CC       macappkit.o
>   CC       macfont.o
>   CC       terminfo.o
>   CC       lastfile.o
>   CCLD     temacs
> codesign -s - -f temacs.tmp
> temacs.tmp: replacing existing signature
> ../build-aux/install-sh -c -d ../etc
> /Library/Developer/CommandLineTools/usr/bin/make -C ../lisp update-subdirs
> cp -f temacs bootstrap-emacs
> rm -f bootstrap-emacs.pdmp
> ./temacs --batch  -l loadup --temacs=pbootstrap
> make[1]: *** [bootstrap-emacs.pdmp] Killed: 9
> make: *** [src] Error 2
> ```
> 
> Is there any way to get more debug data or do you know what might be happening?

I'm getting this same error now (since about this weekend). I attempted the #237 approach of uninstalling homebrew, rm -rf'd my /opt/homebrew and homebrew caches, and reinstalled everything, but I'm still getting the error 

It came up first when I was trying to `brew upgrade` when there was a change from 27.1 to 27.2. Perhaps the 27.2 didn't get whatever patch? 

both `brew install --formula emacs-mac` and the `--head` flag yield the same error.

**Comment by railwaycat** [comment]
The emacs-27.2-mac-8.2 formula no longer have any patch for the signature on Apple Silicon. The upstream already has the fix. I guess that's the reason you met this issue even with `--head`. 

I don't have a suspicion of the root cause and the worse part is I never able to reproduce this issue on my M1 machine. If possible, could you make a tarball of the `~/Library/Logs/Homebrew/emacs-mac/` directory and attach it here? Thanks! Those are the logs of configure and make from homebrew, should not contain any personal information. 

BTW emacs-27.2-mac-8.2 cask includes an Apple ARM64 version.

**Comment by jmhammond** [comment]
Here's my logs [emacs-mac-log.tar.gz](https://github.com/railwaycat/homebrew-emacsmacport/files/6249852/emacs-mac-log.tar.gz)

The cask is working great so far - I'm still new to having a mac so wasn't really clear on brew cask vs. from source.

**Comment by zachfedor** [comment]
having a similar issue, I can post logs if needed. thanks @jmhammond for the temp fix!

**Comment by hkjels** [comment]
I'm facing the same issue with the formula. I wanted to try out `--with-mac-metal` option as it's been touted on reddit lately to be really fast. The formula fails even without that flag though.

**Comment by uenoB** [comment]
I had a similar issue (`temacs` crash with `Killed: 9`) when running `brew install --formula emacs-mac` on my M1 Mac. The following is my workaround.
```diff
--- mituharu-emacs-mac-a124e5d0ccb8/src/Makefile.in.orig	2021-03-27 16:38:19.000000000 +0900
+++ mituharu-emacs-mac-a124e5d0ccb8/src/Makefile.in	2021-04-18 21:51:25.000000000 +0900
@@ -346,7 +346,7 @@
 
 ## ARM Macs require that all code have a valid signature.  Since pump
 ## invalidates the signature, we must re-sign to fix it.
-DO_CODESIGN=$(patsubst arm-apple-darwin%,yes,@configuration@)
+DO_CODESIGN=$(patsubst aarch64-apple-darwin%,yes,@configuration@)
 
 # 'make' verbosity.
 AM_DEFAULT_VERBOSITY = @AM_DEFAULT_VERBOSITY@
```

**Comment by uenoB** [comment]
I guess that you can reproduce this issue by installing the latest version of GNU autoconf.

The root of this issue I found is the mismatch of `config.guess` and
`src/Makefile`. The `emacs-mac` formula invokes `autogen.sh` and updates `config.guess` to the version distributed with autoconf. `config.guess` distributed with GNU autoconf 2.71, which is installed by Homebrew, returns `aarch64-apple-darwin` for M1 Mac. However, `src/Makefile` expects `config.guess` returning `arm-apple-darwin`. Because of this mismatch, `src/Makefile` does not invoke `codesign` to resign `temacs` and thus `temacs` is killed immediately.

**Comment by railwaycat** [comment]
Thanks @uenoB! That must be the reason. I was able to reproduce this error with autoconf 2.71. When I downgrade autoconf from 2.71 to 2.69, the error is gone.

Let me see how I can include a patch for it.

**Comment by railwaycat** [comment]
https://github.com/railwaycat/homebrew-emacsmacport/commit/4d7b7ebbef7de883ae1ebe3b0d951f5d64bf9c91 includes a patch which should able to fix the build error. 

Sorry I thought this issue be fixed by the first commit https://github.com/emacs-mirror/emacs/commit/fda9b3e83a434706c31ab1bee5c15511c0181d5a so I didn't keep tracking the next changes.

**Comment by railwaycat** [comment]
I will close this issue because: 
1. cask build for Apple Silicon is there
2. build error on M1 seems be fixed by the patch.

Feel free to reopen it or create new issue when you see this issue again.
