### ISSUE TITLE
Unable to scale SVG previews

### ISSUE THREAD

**Issue by adam52** [railwaycat/homebrew-emacsmacport#235]
Inline previews of SVGs fail if you attempt to re-scale them in an org-mode buffer. for example:

```
#+ATTR_ORG: :width 200
[[./randomImage.svg]]
```

The width tag works just fine with all other image types. And SVGs will display if the tag is removed...?

**Comment by railwaycat** [comment]
Sorry I'm not able to reproduce this issue on latest version. re-size works for SVG as well as other image format like jpg.

The above image is an SVG and the below one is JPG (width more than 100)
<img width="549" alt="Screen Shot 2021-02-02 at 00 04 09" src="https://user-images.githubusercontent.com/370581/106554832-2f159300-64ea-11eb-9cb6-e3e512f33fa4.png">

**Comment by adam52** [comment]
Ahg. I suppose it would help if I upgraded to 27.1! Thanks @railwaycat it works great :)
