### ISSUE TITLE
 automatically change theme when macOS is on dark theme?

### ISSUE THREAD

**Issue by lk251** [railwaycat/homebrew-emacsmacport#236]
would this be possible?
PS. Thanks for your amazing work, love this emacs version.

**Comment by railwaycat** [comment]
I would like to forward this reward to the developer of emacs mac port: https://bitbucket.org/mituharu/emacs-mac/src/master/.

**Comment by railwaycat** [comment]
The way I know about change theme automatically after system theme is bit tricky:

Emacs mac port supports a list of colors only for macOS system in format: `mac:COLOR-LIST-NAME:COLOR-NAME`.  You can see all the colors by `mac-color-list-alist`. Those colors follows the system theme, for example `mac:system:textColor` is black when macOS is in light theme and it is white when macOS is in dark theme. Try to make your own theme using those colors will give you an Emacs theme fits macOS theme changing. 

I wish there is a way to let you set two Emacs color themes, one for light theme and one for dark theme. I think it's possible but not sure if this feature is/will in Emacs mac port.

**Comment by lk251** [comment]
@railwaycat thanks! this sounds pretty good, i can use it

**Comment by redblobgames** [comment]
I was trying to do this as well, and only got part way. Notes:

1. `(mac-get-preference "AppleInterfaceStyle")` will return `nil` when in light mode and `"Dark"` in dark mode.
2. `(mac-get-preference "AXSClassicInvertColorsPreference" "com.apple.Accessibility")` will return `0` when in normal mode and `1` in inverted colors mode

Emacs mac port should invoke `mac-effective-appearance-change-hook` when either of these changes. You can add a function to this hook to check the current values and switch to the theme you want. (I haven't gotten this far yet)

**Comment by pkryger** [comment]
@redblobgames Your hints helped me developing [this](https://github.com/pkryger/exordium-commontap/blob/a3d6e7b8b908ddf3151b20efe9d7708dea72defa/after-init.el#L141-L154) little thing. It's oriented towards [`modus-themes`](https://protesilaos.com/emacs/modus-themes), but I think it can be tuned to anything else by:
- providing a replacement to `modus-themes-to-toggle` variable: a list in a form of `(LIGHT-THEME DARK-THEME)`
- using appropriate function to unload old theme and load new theme (effectively a replacement to `modus-themes-load-theme`).
