### ISSUE TITLE
brew install errors out on missing .git/hooks/...

### ISSUE THREAD

**Issue by maxheld83** [railwaycat/homebrew-emacsmacport#24]
on 

```
brew tap railwaycat/emacsmacport
brew install emacs-mac
```

I get:

```
==> Installing emacs-mac from railwaycat/homebrew-emacsmacport
==> Cloning http://www.math.s.chiba-u.ac.jp/~mituharu/emacs-mac.git
Updating /Library/Caches/Homebrew/emacs-mac--git
==> Checking out revision emacs-24.5-mac-5.7
==> ./autogen.sh
configure.ac:103: installing 'build-aux/install-sh'
configure.ac:103: installing 'build-aux/missing'
lib/Makefile.am: installing 'build-aux/depcomp'
Installing git hooks...
cp: .git/hooks/applypatch-msg.sample: No such file or directory

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/railwaycat/homebrew-emacsmacport/issues
```

I have:

- `git version 2.3.6`
- OS X 10.10.3
- clear brew update/upgrade
- clear brew doctor

**Comment by maxheld83** [comment]
unsurprisingly, cask works fine.

**Comment by saghaulor** [comment]
I am encountering the same issue.

Brew installation logs can be found here: https://gist.github.com/222aabf2669c1cf58e92

**Comment by saghaulor** [comment]
@maxheld83 is there a way to open the cask version of emacs in the cli much like what is possible from the homebrew tap via?

``` bash
emacs -nw
```

**Comment by saghaulor** [comment]
Please reopen this issue.

**Comment by railwaycat** [comment]
@saghaulor try `alias emacs='<you path of cask apps>/Emacs.app/Contents/MacOS/Emacs'`

**Comment by jacobthemyth** [comment]
@railwaycat That doesn't open the CLI version of emacs, it opens the app.

**Comment by railwaycat** [comment]
@jacobthemyth Sorry, I mean do `emacs -nw` after this alias.
