### ISSUE TITLE
Can I change the help key buttom mapping? 

### ISSUE THREAD

**Issue by KarthikNayak** [railwaycat/homebrew-emacsmacport#241]
Hello currently `CMD Shift /` is mapped to the help menu, any possibility of changing this key mapping? I've mapped `CMD` to `M` and `M-?` is the default for `xref-find-references`.

**Comment by totalbanal** [comment]
[the solution from here worked](https://emacs.stackexchange.com/questions/14823/how-to-disable-command-h-hide-in-emacs-mac-port-railwaycat) for me

`(setq mac-pass-command-to-system nil)`

**Comment by KarthikNayak** [comment]
Good to know! Thanks. 

Can't confirm from my side, I've moved to Linux :)
