### ISSUE TITLE
normal and cask version of emacs-mac

### ISSUE THREAD

**Issue by grolongo** [railwaycat/homebrew-emacsmacport#248]
Hello,

The README mentions two ways of installing emacs-mac with homebrew:
`brew install emacs-mac` and `brew install --cask emacs-mac`

Is there any difference between the two? Does one install GUI Emacs only and the other terminal Emacs only?

Also, the README presents two options `--with-no-title-bars` and `--with-natural-title-bar` but when skimming through the formula I find several others available that are not mentioned in the README like:
`--with-dbus`
`--with-ctags`
`--with-mac-metal`
etc.

Then, when doing `brew options emacs-mac` I find other options which are not mentioned in the README nor the formula, like `--with-imagemagick`, `--with-glib`, etc.

Would it be possible to include all the available options in the README aswell as to know if they are already applied by default?
I think this would greatly reduce the confusion.

Regards

**Comment by zzamboni** [comment]
@grolongo as I understand it (but I'm not the developer), the Casks give you the possibility to install pre-built binaries for 10.13 and above:

- `emacs-mac` Cask: all default options
- `emacs-mac-spacemacs-icon` Cask: default options with Spacemacs icon

On the other hand, the Formula allows you to build with any options you need.

As for the options, I don't know the full description of all of them, but FWIW, these are the ones I am using at the moment:

```
brew install emacs-mac --with-rsvg --with-imagemagick --with-dbus --with-mac-metal --with-sjrmanning-icon
```
(Note: `--with-sjrmanning-icon` is not part of the main Formula yet, it's introduced by PR #251 which I submitted yesterday)

**Comment by railwaycat** [comment]
Hi @grolongo, thanks for the remind! I will see how I can update the README file to include the description of options, or put them into a wiki page. Meanwhile you can see a short description for each options from `brew info emacs-mac`, I hope that will helps you a bit.

@zzamboni Thanks for the icon and PR:)

**Comment by grolongo** [comment]
thank you guys for the explanations, and the wiki is a nice addition!
