### ISSUE TITLE
emacs-28 (native-comp)

### ISSUE THREAD

**Issue by shaunsingh** [railwaycat/homebrew-emacsmacport#256]
Hi, is it possible to create a patch that allows you to build emacs-mac on emacs28/native-comp? I love the look and feel of emacs-mac, but its quite slow compared to emacs28, it would be nice to have the best of both worlds

**Comment by kreisys** [comment]
This is just the homebrew formula repo... The actual macport  is at https://bitbucket.org/mituharu/emacs-mac and he seems to only be releasing Mac ports of released versions 🤷‍♀️

**Comment by railwaycat** [comment]
as @kreisys said, Mitsuharu Yamamoto, the developer of emacs mac port, track the released and pretest release only. So the current developing branch "work" is tracking Emacs-27.2. 

I guess once emacs-28 entering pre-test, the native-comp option may comes to emacs mac port. But for now, unfortunately the answer is no.

**Comment by kresdjan** [comment]
Any news on this?

**Comment by willbchang** [comment]
@kresdjan check #274
