### ISSUE TITLE
Cmd and Alt switching on OSX preferences has no effect.

### ISSUE THREAD

**Issue by JavierMares** [railwaycat/homebrew-emacsmacport#27]
Hi Railwaycat,

CMD and ALT switching, which I configured in OSX preferences, doesn't seem to work. 

In other words, command is command, and alt is alt, despite my configuration of cmd = alt, and alt = cmd.

Thank you,
Javier

**Comment by railwaycat** [comment]
Please take a look at https://gist.github.com/railwaycat/3498096, that might able to give you little help:)

**Comment by JavierMares** [comment]
Thank you very much! :-)
