### ISSUE TITLE
Cask version of emacs-27.2-mac-8.3 cannot open without jansson

### ISSUE THREAD

**Issue by ywwry66** [railwaycat/homebrew-emacsmacport#270]
Hi, I just updated from 8.2 to 8.3 and suddenly Emacs refuses to open with the following error:
```
dyld[31388]: Library not loaded: /opt/homebrew/opt/jansson/lib/libjansson.4.dylib
  Referenced from: /Applications/Emacs.app/Contents/MacOS/Emacs
  Reason: tried: '/opt/homebrew/opt/jansson/lib/libjansson.4.dylib' (no such file), '/usr/lib/libjansson.4.dylib' (no such file)
```
After installing `jansson`, I was able to use Emacs normally. Do you know what caused this change?

**Comment by railwaycat** [comment]
Hi, can I confirm that you are on Apple Silicon Mac? This might be a bug in my build script which is not able to pick up homebrew libraries under the new directory `/opt/homebrew`. Let me take a look..

**Comment by ywwry66** [comment]
Yes I am on Apple silicon. Emacs.app is able to pick up libjansson after I did 'brew install jansson'. The problem sounds to me like 'jansson' was optional before but now it is a required dependency.

**Comment by railwaycat** [comment]
Yes. Not only `jansson` but also `gnutls`.

I can make an update on cask build to fix this very soon.

**Comment by railwaycat** [comment]
Hi @ywwry66, could you try a `brew update` && `brew upgrade`? The latest version "emacs-27.2-mac-8.3.1" should fixed the dependency issue. Sorry for the inconvenient and thanks to let me know the issue!

**Comment by ywwry66** [comment]
I can confirm it is fixed. Thanks!

**Comment by ywwry66** [comment]
I just noticed that after installing the new version, the icon in `/Application` becomes spacemacs, while the icon in Launchpad.app remains the classical emacs style.

**Comment by railwaycat** [comment]
Sorry it's my mistake again..I should put everything in script first before make a release:( Should be good now and in the future. Could you try `brew update` again and `brew reinstall --cask emacs-mac`? I updated those files instead of bump release number since icon is a minor issue.

**Comment by ywwry66** [comment]
Thanks for the quick fix. It works properly now.
