### ISSUE TITLE
Cannot install from source - mac-arm-diff.patch cannot be applied

### ISSUE THREAD

**Issue by pkryger** [railwaycat/homebrew-emacsmacport#273]
`brew install --HEAD emacs-mac` fails for me. It seems like `mac-arm-fix.diff` is not applicable since [this commit](https://bitbucket.org/mituharu/emacs-mac/commits/d6e59af3d648a1d5e7e7617b50c7d712795d0663). 

I managed to building on Intel by simply commenting out the `mac-arm-fix.diff` patch in formula, but I don't have an M1 to check if the commit is sufficient.

**Comment by railwaycat** [comment]
I noticed a recent commit from upstream https://bitbucket.org/mituharu/emacs-mac/commits/d6e59af3d648a1d5e7e7617b50c7d712795d0663 on the codesign. Which may means this patch is no longer needed. 

Let me have a try on both platforms and I will get back to you.
