### ISSUE TITLE
M1 build with native comp won't start 

### ISSUE THREAD

**Issue by restfuladi** [railwaycat/homebrew-emacsmacport#276]
I ran `brew install emacs-mac --HEAD --with-native-comp` and copied the .app to /Applications. When launching from Finder nothing happens. I ran `/Applications/Emacs.app/Contents/MacOS/Emacs -q` and got:

```Error using execdir /Applications/Emacs.app/Contents/MacOS/:
emacs: dlopen(/Applications/Emacs.app/Contents/MacOS/../native-lisp/28.0.91-9d9d226c/preloaded/window-0d1b8b93-dd327956.eln, 0x0001): tried: '/Applications/Emacs.app/Contents/MacOS/../native-lisp/28.0.91-9d9d226c/preloaded/window-0d1b8b93-dd327956.eln' (no such file), '/usr/local/lib/window-0d1b8b93-dd327956.eln' (no such file), '/usr/lib/window-0d1b8b93-dd327956.eln' (no such file)```

**Comment by pkryger** [comment]
Have you added a symlink as per point 2 in [comment](https://github.com/railwaycat/homebrew-emacsmacport/issues/274#issuecomment-1011445527)?

**Comment by restfuladi** [comment]
> Have you added a symlink as per point 2 in [comment](https://github.com/railwaycat/homebrew-emacsmacport/issues/274#issuecomment-1011445527)?

No just copied the .app folder. Is there an issue with doing that?
