### ISSUE TITLE
Add xwidgets support?

### ISSUE THREAD

**Issue by ErnestDong** [railwaycat/homebrew-emacsmacport#285]
emacs 28 has supported xwidget on macOS now. here's the [NEWS](https://git.savannah.gnu.org/cgit/emacs.git/tree/etc/NEWS?h=emacs-28#n3920=)  . 

And I suceeded in compiling emaacs with option `--with-starter --with-rsvg --with-dbus --with-emacs-big-sur-icon --with-glib --with-imagemagick --with-mac-metal --with-native-comp --with-natural-title-bar --with-xwidgets` by this commit:
https://github.com/ErnestDong/homebrew-emacsmacport/commit/3d30620eddf5a074b8d6e34dd604fee1fc0aff66

Here's the result
<img width="1552" alt="截屏2022-04-07 15 18 43" src="https://user-images.githubusercontent.com/45593614/162143173-d1bb41f6-01c5-445d-867a-cbb3a9b82423.png">

However I failed to run github actions and have no idea why. 

Maybe #79 is finally closed now

**Comment by railwaycat** [comment]
Great! Do you mind to submit a PR with your changes? It looks good to me and we can figure out the Github Actions failure later.

**Comment by ErnestDong** [comment]
done in #291. Thank you for your works

**Comment by nipuna-perera** [comment]
hey this looks cool! Did you follow some kind of a guide to set this up?

**Comment by ErnestDong** [comment]
well. I'm Chinese. Chinese emacser has a discourse. I wanna check out what's new in emacs-28 and  I saw https://emacs-china.org/t/emacs-28/18806, which introduce new features.

**Comment by chunsj** [comment]
The packages in Release section does not have xwidgets support? It says it was not compiled with xwidgets support.

**Comment by ErnestDong** [comment]
currently not.

**Comment by quarkquartet** [comment]
Has this feature been merged to the master branch? I run the `brew tap` again and it still told me that there is no option `--with-xwidgets`.

**Comment by ErnestDong** [comment]
Nope. you can use `brew edit emacs-mac` and add the #291 diffs for now.

**Comment by chunsj** [comment]
I hope binary release version could have this feature as default, someday. The only exception I have to use other than emacs is web browser :-)

**Comment by ilyaw39** [comment]
> I hope binary release version could have this feature as default, someday. The only exception I have to use other than emacs is web browser :-)

I have the same demand as yours. (^_^)v

Hope this PR can be merged soon. It is glad to hear about such improvement with fancy features coming out these days. And I also appreciate with the the hardworking of the maintainers. ❤️

**Comment by railwaycat** [comment]
Sorry for the delay! I will merge the PR no later than this weekend and look at a possible Cask build with it.

**Comment by chunsj** [comment]
Wow, I hope the binary release with xwidget support could be released as well.

**Comment by ErnestDong** [comment]
Stop urging railwaycat and test on [binary](https://github.com/ErnestDong/homebrew-emacsmacport/releases/tag/untagged-53f239e8b75c0bbce22a), please.

**Comment by chunsj** [comment]
Oh, I did not want to urge railwaycat. T_T Sorry.

**Comment by ErnestDong** [comment]
oops sorry. now fixed in new url https://github.com/ErnestDong/homebrew-emacsmacport/releases/tag/xwidget

**Comment by railwaycat** [comment]
I updated a cask only release with xwidgets. A `brew upgrade` should able to get it -- the only exception is Big Sur on Apple Silicon, unfortunately. The reason in #289.
