### ISSUE TITLE
Cask for Emacs 28.1/9.0

### ISSUE THREAD

**Issue by PatrickNorton** [railwaycat/homebrew-emacsmacport#287]
The formula was updated yesterday, but the cask still seems to be on 27.2.

**Comment by railwaycat** [comment]
Yes, it is true:(

I was trying to create a cask with native-comp, but it fails on some tests so I have to switch back, which took extra time. The cask update should be ready before the weekend, but without native-comp.

**Comment by PatrickNorton** [comment]
That stinks :(. Would it be possible to create a second, "use-at-your-own-risk" cask with native-comp or is that too difficult?

**Comment by railwaycat** [comment]
cask for 28.1-mac-9.0 updated. Discussion on native-comp will continue on above issue.
