### ISSUE TITLE
Suggestion: change the build flag --with-native-comp into --with-native-compilation

### ISSUE THREAD

**Issue by drshapeless** [railwaycat/homebrew-emacsmacport#296]
Since the Emacs repo has renamed the "--with-native-comp" flag into "--with-native-compilation", you can see it by `./configure --help`, it is better for the tap to be consistent with the mainstream Emac term to reduce ambiguity. 

Even the macport repo has renamed "--with-native-comp" into "--with-native-compilation".

**Comment by jasonm23** [comment]
Do please note that to get this fixed, a PR is the simplest option for you.

**Comment by railwaycat** [comment]
This issue fixed by PR #306 and commit 81bff3007be2894dd335472ef5e1683da36c4b3f. Thank you @manuraj17 for the PR!
