### ISSUE TITLE
libgccjit missing from Application

### ISSUE THREAD

**Issue by poetinger** [railwaycat/homebrew-emacsmacport#302]
I used the following command (discovered through #274 ):
`❱❱❱ brew install emacs-mac --HEAD --with-native-comp --with-mac-metal`

Afterwards, I am in a strange situation where the `emacs` command opens emacs properly in a GUI. However input is not forwarded to the application (and instead shows up in terminal when emacs is closed). Emacs does not show up in `/Applications`. If I attempt to open Emacs through command+space, I receive an error with the following termination reasons:

```
Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /opt/homebrew/*/libgccjit.so.0
Referenced from: /Users/USER/*/Emacs.app/Contents/MacOS/Emacs
Reason: tried: '/opt/homebrew/*/libgccjit.so.0' (no such file), '/usr/local/lib/libgccjit.so.0' (no such file), '/usr/lib/libgccjit.so.0' (no such file), '/opt/homebrew/Cellar/libgccjit/11.3.0_1/lib/gcc/11/libgccjit.so.0' (no such file), '/usr/local/lib/libgccjit.so.0' (no such file), '/usr/lib/libgccjit.so.0' (no such file)
(terminated at launch; ignore backtrace)
```

I couldn't find anything about generating this library, so any help would be appreciated.

**Comment by jeff-tcare** [comment]
Did you try: `brew install libgccjit`?

**Comment by poetinger** [comment]
Yes, `libgccjit` was installed. But I will close this now, as it was discovered that a clash in installations (somehow) between old compiled emacs, nix installed emacs, and brew installed emacs was occurring. Apparently previous uninstalls were not complete.
