### ISSUE TITLE
cask: start bin/emacs in CLI

### ISSUE THREAD

**Issue by ffffwh** [railwaycat/homebrew-emacsmacport#308]
Currently, I am doing `cd bin; mv emacs emacs-gui`
and create the script bin/emacs with `/Applications/Emacs.app/Contents/MacOS/Emacs.sh -nw "$@"`

Could you make an install option for this? Or make it default, if no one expects to start a GUI emacs from terminal.

**Comment by railwaycat** [comment]
Homebrew doesn't allow a cask to accept options. 

I'm not sure if I should make the `-nw` option default, since this is the consistent behavior for Emacs on all platform. Use a personal starter script is always a workaround, which you already have.

**Comment by railwaycat** [comment]
Not sure if an alias would help you from replacing the `$(brew --prefix)/bin/emacs` symbolic link every time?

For example:

```
alias emacs='emacs -nw'
```

**Comment by ffffwh** [comment]
It also needs
```
export EDITOR="emacs -nw"
```
I am not sure whether this works consistently.
