### ISSUE TITLE
odie causes `brew search` to fail

### ISSUE THREAD

**Issue by patmaddox** [railwaycat/homebrew-emacsmacport#309]
[This line](https://github.com/railwaycat/homebrew-emacsmacport/blob/2db483db12e7fdd4aa4f95311365090434bfb3dc/Casks/emacs-mac-spacemacs-icon.rb#L6) causes `brew search` to completely fail on Catalina, with the given error message. There is no indication that this tap is responsible. I found it via google and untapped it.

**Comment by railwaycat** [comment]
Thank you for point it out! I can confirm this is an issue on my side. I will delivery a fix very soon.

**Comment by railwaycat** [comment]
This issue should be fixed on ab49db149e044c3739ce9efd4468c1d923195676. Sorry for the inconvenience!
