### ISSUE TITLE
Cannot open a file with Emacs.app from Terminal

### ISSUE THREAD

**Issue by kdmsnr** [railwaycat/homebrew-emacsmacport#315]
I'd like to open a file with Emacs.app from Terminal.app.

I symbolic linked like this:

```sh
% which emacs
emacs: aliased to open -a /opt/homebrew/opt/emacs-mac/Emacs.app
```

then, I tried to open a file.

```sh
% touch tmp.txt
% emacs tmp.txt
```
I can open the Emacs window, but I cannot open the file.

Are there any workarounds?

**Comment by railwaycat** [comment]
You can take a look at this thread for starter scripts: https://gist.github.com/railwaycat/4043945. Although for a regular file, this alias should work. Could you also take a look at `*Messages*` and `*Warnings*` buffers to see if clue?

**Comment by kdmsnr** [comment]
I have looked at that script, but the "open -a" part does not work well.

```
% open -a /opt/homebrew/opt/emacs-mac/Emacs.app test.txt 
# nothing happen
```

Emacs For Mac OS X (https://emacsformacosx.com/) works well.

```
% open -a /Applications/Emacs.app test.txt
# open the file
```
