### ISSUE TITLE
Difference between MacPorts versions?

### ISSUE THREAD

**Issue by kresdjan** [railwaycat/homebrew-emacsmacport#318]
I can't seem to spot the difference `emacs-mac-app` and `emacs-mac-app-devel`. I would assume the the development version is GNU Emacs 29?

**Comment by railwaycat** [comment]
Sorry I'm not the maintainer of `emacs-mac-app` and `emacs-mac-app-devel` on macports. This is a repo only for Homebrew. 

As my understanding from their script, `emacs-mac-app-devel` is build from the latest of `work` branch: the developing branch of emacs mac port. It is still based on upstream 28.2, but with the latest changes from author which are not yet be released.
