### ISSUE TITLE
Error: Options --cask and --with-no-title-bars are mutually exclusive

### ISSUE THREAD

**Issue by tillydray** [railwaycat/homebrew-emacsmacport#319]
When I run `brew install --cask railwaycat/emacsmacport/emacs-mac --with-native-comp --with-no-title-bars` I get the error `Error: Invalid usage: Options --cask and --with-no-title-bars are mutually exclusive.` When I remove `--with-no-title-bars` I get `Error: Invalid usage: Options --cask and --with-native-comp are mutually exclusive.`

I would like to install the cask with both of those flags. Is that possible? If so, how?

**Comment by railwaycat** [comment]
Unfortunately Homebrew cask is not able to accept any options. If you would like to install an Emacs-mac-port with those options, you can run the command without `--cask` to install from formula (compile from source code). The cask version by default is build without the above options. 

```
brew install railwaycat/emacsmacport/emacs-mac --with-native-comp --with-no-title-bars
```

**Comment by tillydray** [comment]
Thanks for the quick response, I didn't realize all flags were unallowed with `cask`
