### ISSUE TITLE
Probable bug with with-eval-after-load

### ISSUE THREAD

**Issue by angrybacon** [railwaycat/homebrew-emacsmacport#32]
Not sure if this is about home-emacsmacport, but someone on ES hinted that it could be a bug.

To sum it up, I tried to split even more my configuration files and took for model Steve Purcell's dot files I believe (making each partial a package on its own and `require` them in init.el). I then tried to wrap all package-related configuration with `with-eval-after-load`.

Here is the link to the ES post: http://emacs.stackexchange.com/questions/12487/when-should-i-use-with-eval-after-load-in-my-configuration-files

**Comment by angrybakon** [comment]
I can't replicate the issue when using [use-package](https://github.com/jwiegley/use-package).

**Comment by angrybakon** [comment]
Actually I can, here is [my current configuration][10]. I have an issue where `(load-theme 'zenburn t)` overwrites my configuration for  `helm`'s faces, so I tried to move up `(use-package init-theme)`. If I move it up to the line 63, I will experience the same issue as described in my ES post.

![screen shot 2015-06-01 at 14 10 58](https://cloud.githubusercontent.com/assets/5608624/7912472/16e28f02-0868-11e5-9522-bf1e5d8eff82.png)

[10]: https://bitbucket.org/angrybacon/dotemacs/src/48017518f4da1c3e7256faaa6f4cd6ac8a8a689b/init.el?at=master

**Comment by railwaycat** [comment]
Sorry, I will close this issue since it's a long time ago. Besides I believe this issue might not relates to the homebrew formula or packing? You are welcome to open a new issue if you still see this issue on the most recent version, thanks!
