### ISSUE TITLE
Support org-protocol in CFBundleURLTypes

### ISSUE THREAD

**Issue by kickingvegas** [railwaycat/homebrew-emacsmacport#325]
In the `emacs-mac` repo, [org-protocol](https://orgmode.org/manual/Protocols.html) is natively supported as seen in the template file `Info.plist.in`:

https://bitbucket.org/mituharu/emacs-mac/src/7ec68b6ffd2d5cfdc659c64d83b1e0f613a76b4a/mac/templates/Info.plist.in#lines-595

Request is to add native `org-protocol` support to the `homebrew-emacsmacport` repo. Note that the Mitsuharu repo somehow natively supports org-protocol, bypassing the need to run emacs server.

**Comment by fintelkai** [comment]
This does work out of the box with `homebrew-emacsmacport`. Have you tried it? If you inspect `/opt/homebrew/Cellar/emacs-mac/emacs-28.2-mac-9.1/Emacs.app/Contents/Info.plist`, you'll find that very same entry. And entering, for example,`open "org-protocol://store-link?url=https%3A%2F%2Forgmode.org%2Fmanual%2FThe-store_002dlink-protocol.html"` in a terminal sends this successfully to emacs without a server running.

**Comment by kickingvegas** [comment]
@fintelkai interesting. I've gotten conflicting input on this. Will investigate further.

**Comment by kickingvegas** [comment]
@fintelkai actually the issue is with https://github.com/d12frosted/homebrew-emacs-plus 
Thanks for verifying all the same! 

Closing issue.
