### ISSUE TITLE
FD_SETSIZE Config option needed

### ISSUE THREAD

**Issue by jeff-phil** [railwaycat/homebrew-emacsmacport#338]
In large repos, the LSP File Watchers may open a large number of `files descriptors` to monitor for changes per the [LSP spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#fileSystemWatcher) using filenotify.el.  On macos, the number of file descriptors is low and Emacs then defaults to 1024.  This causes the file descriptors to quickly be exhausted, causing issues and/or decreased functionality.

Even with easy ulimit changes, the size in emacs can only be changed with a recompile and a setting such as: `CFLAGS="-DFD_SETSIZE=10000 -DDARWIN_UNLIMITED_SELECT"`.  A very good discussion: https://en.liujiacai.net/2022/09/03/emacs-maxopenfiles/.

For average users, recompiling emacs to increase the number may be a bit daunting.

Propose a new feature option like: `--with-large-file-descriptors` be added.

**Comment by Patryk27** [comment]
fwiw, there's also a patch for that:
https://lists.gnu.org/archive/html/emacs-devel/2022-05/msg00115.html

I think the patch is a bit better since it doesn't require modifying system's ulimits (which I think you must do in order for `FD_SETSIZE` to actully work).

**Comment by railwaycat** [comment]
@Patryk27 This patch looks reasonable, there is discussion under the mail thread on X libraries but looks like won't affect on macOS. Let me finish the thread first and see if we can include this patch in build.

**Comment by celsobonutti** [comment]
Any updates on this? I've been suffering with it for a while :(

**Comment by scohen** [comment]
I spent some time tracking down and fixing this issue locally, I would really appreciate an option to automatically do this. Would you accept a PR?

**Comment by railwaycat** [comment]
@scohen Yes, please. PR welcome!

Sorry for keep this issue long open.

**Comment by scohen** [comment]
@railwaycat, I added #365 

I wanted to make this option configurable, but was unable to figure out how to do so, so I defaulted to 10,000 open files.

**Comment by railwaycat** [comment]
Thanks @scohen! Homebrew can't accept an option more than on/off. If we are not going to hack the Emacs code, providing a hardcode value maybe our only option.

**Comment by scohen** [comment]
Ok, so i wasn't just missing the obvious. 10,000 seems reasonable to me (and the previous value of 1,000 seems very, very low --especially since language servers are a thing)
