### ISSUE TITLE
Full screen not working with 10.11 El Capitan beta 2

### ISSUE THREAD

**Issue by mariusk** [railwaycat/homebrew-emacsmacport#34]
Wild guess, it is related to the new features described as "full screen split view" and similar. Yes, I realize this repo is primarily for the Homebrew related stuff, but the raw git repo from the author of emacs-mac only supports dumping information "downstream". :-)

**Comment by mariusk** [comment]
Just tested the standard homebrew emacs recipe, building from source using:

    brew install emacs --HEAD --use-git-head --cocoa --srgb

It works fine (doesn't have the problem reported in this issue).

**Comment by akivaschoen** [comment]
I’ve been able to make it work by dragging the Emacs window up into Spaces bar in Mission Control rather than using the green traffic button. It’s a work-around, sure, but better than nothing.

**Comment by railwaycat** [comment]
I tried on El Capitan beta 3 (15A216g) today and looks like the latest mac-5.9 working OK...Both split view and fullscreen. 

Just realized I have typos on recent check-in comments :( "emacs-24.5-mac-5.8" should be "emacs-24.5-mac-5.9"...

**Comment by favadi** [comment]
The latest version seems to break the green button full screen again, using `toggle-frame-fullscreen` still works, though.

**Comment by wwkeyboard** [comment]
On OSX `10.11.2 (15C50)` using emacs head(installed using the same method @mariusk described) it won't go fullscreen with the green button, `toggle-frame-fullscreen`, or by selecting emacs as the other side of a split pane view.

**Comment by railwaycat** [comment]
Sorry I will close this issue because of the age. You are welcome to open a new one if this issue still consistent on the latest version.

**Comment by Leyls** [comment]
Sorry I am using 12.3.1 Monterey and the green button doesn't perform system full screen operation. I am using the notch version Mac. So if I toggle the fullscreen the notch would cover some texts.
Is there some ways to use system full screen operation on emacs?
I installed the emacs-mac from homebrew.
