### ISSUE TITLE
Cask formulas should transition from using appcast to livecheck

### ISSUE THREAD

**Issue by ViktorHaag** [railwaycat/homebrew-emacsmacport#341]
This morning when updating my homebrew environment, I repeatedly saw this error:
```
Warning: Calling the `appcast` stanza is deprecated! Use the `livecheck` stanza instead.
Please report this issue to the railwaycat/emacsmacport tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/railwaycat/homebrew-emacsmacport/Casks/emacs-mac-spacemacs-icon.rb:23
```

I'm not sure I understand the migration needed here well enough to submit a PR myself. It seems like the formula used the `atom` version of the releases page constructed by Github as the [information source for the `appcheck` stanza](https://github.com/railwaycat/homebrew-emacsmacport/blob/6e239e76b4e631c981ea815dc1c0518623bb7b07/Casks/emacs-mac-spacemacs-icon.rb#L23), and now that stanza needs replacing with a `livecheck` stanza that depends on the same atom file for release information. I haven't been able to find sufficient information about doing that migration to suggest a PR myself, unfortunately.

I suspect this affects the `emacs-mac` cask as well, since the formula [also still depends on the `appcheck` stanza](https://github.com/railwaycat/homebrew-emacsmacport/blob/6e239e76b4e631c981ea815dc1c0518623bb7b07/Casks/emacs-mac.rb#L23).

**Comment by dpassen** [comment]
Looks like it should simply be:
```rb
livecheck do
  url 'https://github.com/railwaycat/homebrew-emacsmacport/releases.atom'
  strategy :sparkle
end
```

How to test?

**Comment by ViktorHaag** [comment]
Hmm... well, I tried hand-editing the cask formula locally that live in `/usr/local/Homebrew/Library/Taps/railwaycat/homebrew-emacsport/Casks/...` so that the middle section looks like this:
```
  # comment out the appcast line
  # appcast 'https://github.com/railwaycat/homebrew-emacsmacport/releases.atom'
  name 'Emacs-mac'
  homepage 'https://bitbucket.org/mituharu/emacs-mac.git'
  desc "YAMAMOTO Mitsuharu's Mac port of GNU Emacs"

  # add in the suggested livecheck stanza snippet
  livecheck do
    url 'https://github.com/railwaycat/homebrew-emacsmacport/releases.atom'
    strategy :sparkle
  end
```

Then, I issue `brew livecheck --debug --cask emacs-mac`.

However, that gives me an error of "versions not found". So I updated the strategy to be more simply: `strategy :git` instead of `strategy :sparkle`. That produces this output:

```
~/src/work/d2l/valence-api-docs : [main] brew livecheck --debug --cask emacs-mac

Cask:             emacs-mac
Livecheckable?:   Yes

URL:              https://github.com/railwaycat/homebrew-emacsmacport/releases.atom
URL (processed):  https://github.com/railwaycat/homebrew-emacsmacport.git
Strategy:         Git

Matched Versions:
24.5-mac-5.10, 24.5-mac-5.11, 24.5-mac-5.13, 24.5-mac-5.14, 24.5-mac-5.15, 24.5-mac-5.16, 24.5-mac-5.17, 24.5-mac-5.18, 24.5-mac-5.7, 24.5-mac-5.8, 24.5-mac-5.9, 24.5-rc1-mac-5.6, 24.5-rc2-mac-5.6, 24.5-rc3-mac-5.6, 25.1-mac-6.0, 25.1-mac-6.1, 25.1-rc1-mac-5.90, 25.1-rc2-mac-5.91, 25.2-mac-6.3, 25.2-mac-6.4, 25.2-mac-6.5, 25.2-mac-6.6, 25.2-rc1-mac-6.2, 25.3-mac-6.7, 25.3-mac-6.8, 26.1-mac-7.0, 26.1-mac-7.1, 26.1-mac-7.2, 26.1-rc1-mac-6.90, 26.2-mac-7.6, 26.2-mac-7.6.1, 26.2-rc1-mac-7.5, 26.3-mac-7.7, 26.3-mac-7.8, 26.3-mac-7.9, 26.3-mac-7.9.1, 26.3-rc1-mac-7.7, 27.1-mac-8.0, 27.1-mac-8.0.1, 27.1-mac-8.1, 27.2-mac-8.2, 27.2-mac-8.3, 27.2-mac-8.3.1, 28.1-mac-9.0, 28.1-mac-9.0.1, 28.2-mac-9.1

emacs-mac: emacs-28.2-mac-9.1 ==> 28.2-mac-9.1
```

With my hand-edited local tap's cask formulas, I was able to uninstall and reinstall from both the `emacs-mac` and `emacs-mac-spacemacs-icon` cask formulas.


So.... maybe the simple stanza with the `:git` strategy is what's needed here?

Like you, though, I have no real clue how to _test_ this, so I'm wary about putting up a PR like that...

**Comment by dpassen** [comment]
Seems like `strategy: :git` is unnecessary, and the same information is retrieved with just the `url` set.

**Comment by ViktorHaag** [comment]
> Seems like `strategy: :git` is unnecessary, and the same information is retrieved with just the `url` set.

I think you are correct; reading the homebrew documentation, I'm lead to believe that `strategy :git` is the default strategy. Whether it's good to lean on that, or be explicit, I'm not sure -- I can see pros and cons either way.

**Comment by mpolden** [comment]
I created #342 before I saw this issue. Is appcast/livecheck needed at all though? Releases and the cask formula both live in this repository, so simply updating the tap will discover any upgrades.

**Comment by ViktorHaag** [comment]
> I created #342 before I saw this issue. Is appcast/livecheck needed at all though? Releases and the cask formula both live in this repository, so simply updating the tap will discover any upgrades.

You may be entirely correct. Either way, something needs doing so that my brew stops burping warning messages at me. If your PR fixes the situation in a clean way, that seems just fine to me.

**Comment by dpassen** [comment]
Looks like we can close this @ViktorHaag

**Comment by ViktorHaag** [comment]
OK; will close.
