### ISSUE TITLE
emacs29.1 ?

### ISSUE THREAD

**Issue by kekeimiku** [railwaycat/homebrew-emacsmacport#346]
please support official 29.1 release. Thanks! https://www.gnu.org/savannah-checkouts/gnu/emacs/emacs.html#Releases

**Comment by railwaycat** [comment]
29.1 will be there once the upstream release is available: https://bitbucket.org/mituharu/emacs-mac/downloads/?tab=tags (cask build may have a short delay). 

Meanwhile install from formula by `--HEAD` should be the most close one to 29.1.

**Comment by galeo** [comment]
It seems that the configure program couldn't find the brew installed **tree-sitter**(version 0.20.8) when install emacs-mac with the `--HEAD` option(which would install the latest `work` branch with 29.1 merged). It should build with tree-sitter if tree-sitter is available. When I try to install [`emacs-plus@29`](https://github.com/d12frosted/homebrew-emacs-plus#emacs-29), it can successfully find the brew installed tree-sitter and build with it. I can not figure out what's wrong, any help? 

Thanks.

**Comment by ksqsf** [comment]
The upstream released 29.1 today: https://lists.gnu.org/archive/html/emacs-devel/2023-08/msg00076.html

**Comment by railwaycat** [comment]
Thanks to let me know @ksqsf, the formula is updated by #349. Casks will a bit delay but I hope in this weekend.
