### ISSUE TITLE
Emacs.app not working through launcher

### ISSUE THREAD

**Issue by elemakil** [railwaycat/homebrew-emacsmacport#35]
Hi,

I am a fresh Mac user (Yosemite 10.10.4) so pleace bear with me and help me through my non-Mac ignorance.

I installed `emacs-mac` through brew using the _normal_ commands, i.e.
> brew tap railwaycat/emacsmacport
> brew install emacs-mac

Afterwards I can start `Emacs.app` by opening a terminal and executing
> open /usr/local/Cellar//emacs-mac/emacs-24.5-z-mac-5.8/Emacs.app

as expected, starting `Emacs.app` through _spotlight search_ does not work. When I copy (**not** move) `Emacs.app` to `/Applications` it shows up in _spotlight search_, however, launching it fails; nothing happens.

I fired up the log console (i.e. `Console.app`) and filered for _"emacs"_, then re-launched `Emacs.app` through _spotlight search_; the following message shows up:

```
06/07/2015 12:18:59.625 com.apple.xpc.launchd[1]: (org.gnu.Emacs.92048[75135]) Service exited with abnormal code: 126
```

I have uninstall and re-installed `emacs-mac` and I have also done so using various combinations of the `--with-*` flags. Nothing changes. 

Launching from the command line is an annoyance, I'd be grateful if you could help!

**Comment by elemakil** [comment]
Apparently this can be solved by something as simple as rebooting ... I'm very sorry for the noise I've created but I did not expect that program launching requires a reboot.

**Comment by railwaycat** [comment]
well @elemakil, I don't think this installation needs a rebooting too in normal case...

This `abnormal code: 126` happens usually when something is not install/uninstall properly, so I guess you have other version of Emacs installed in `/Application` before?
