### ISSUE TITLE
Support for multiple versions

### ISSUE THREAD

**Issue by albertsj1** [railwaycat/homebrew-emacsmacport#352]
With the recent change of this formula to build emacs 29 rather than 28, and DoomEmacs not yet supporting 29, this has broken Emacs for me.  This homebrew formula only supports the current version, unlike others, such as [emacs-plus][1], which supports multiple versions for backwards compatability.

Would it be possible to add add the old commit of the emacs-mac.rb file with Emacs28, to the repo as emacs-mac@28.rb so version 28 can easily be installed?

Thanks

[1]: https://github.com/d12frosted/homebrew-emacs-plus/tree/master/Formula

**Comment by sevillaarvin** [comment]
I'm not sure but I think it's possible to use a manually repointed commit:

```shell
cd /usr/local/Homebrew/Library/Taps/railwaycat/homebrew-emacsmacport/
git checkout abcd1234
brew install emacs-mac
```

**Comment by albertsj1** [comment]
> I'm not sure but I think it's possible to use a manually repointed commit:
> 
> ```shell
> cd /usr/local/Homebrew/Library/Taps/railwaycat/homebrew-emacsmacport/
> git checkout abcd1234
> brew install emacs-mac 
> ```
 
Thank you.  I forgot to mention, I did do this, and it works.  It's just not an ideal solution.  It would be great if the tap supported multiple versions like emacs-plus.  This would allow me to have emacs 28 and 29 installed at the same time so I can test 29, while letting 28 continue to be my daily driver.

**Comment by albertsj1** [comment]
@railwaycat  Thank you so much for adding support for easily installing emacs 28.
