### ISSUE TITLE
Huge title bar on macOS Sonoma 14.0

### ISSUE THREAD

**Issue by c0494133d4** [railwaycat/homebrew-emacsmacport#362]
I am using the prebuilt `emacs-29.1-mac-10.0-arm64-13.4.zip`.

![Screenshot 2023-09-27 at 18 27 12](https://github.com/railwaycat/homebrew-emacsmacport/assets/41767537/7d9ea814-f1a3-408b-a4cf-afb21c41c072)

How to reduce the size to a normal one (without hiding title bar completely)?

**Comment by railwaycat** [comment]
Hi @c0494133d4, do you mind start Emacs by `/Applications/Emacs.app/Contents/MacOS/Emacs -q` to see if this issue consistent?

**Comment by c0494133d4** [comment]
@railwaycat `Emacs -q` and hide menu bar. Then the problem was solved.

The problem is due to that I put `(tool-bar-mode 0)` in `early-init.el`

**Comment by liebkne** [comment]
@railwaycat How to avoid the huge title bar in custom build? When I start emacs with `/usr/local/opt/emacs-mac/Emacs.app/Contents/MacOS/Emacs`, the title bar is huge. 

Built options: `--with-dbus --with-glib --with-imagemagick --with-mac-metal --with-native-comp --with-xwidgets --with-natural-title-bar`

**Comment by adamliter** [comment]
I also have an extremely large title bar with macOS Sonoma, compared to previous macOS versions. It seems like the tool bar images are larger in macOS Sonoma or something like that and that is what is causing the difference?

If I start `emacs-mac` like `/Applications/Emacs.app/Contents/MacOS/Emacs -q &` (after having installed on macOS Sonoma with `--with-natural-title-bar`), then I see this:
![image](https://github.com/railwaycat/homebrew-emacsmacport/assets/4974404/b7ffa15c-1c41-4b2f-828c-b6cf16446cc5)

However, if I start it like `/Applications/Emacs.app/Contents/MacOS/Emacs -q --eval '(tool-bar-mode 0)' &`, then I see this:

![image](https://github.com/railwaycat/homebrew-emacsmacport/assets/4974404/0b7841a2-437a-421c-a90a-7f14000cdb22)

If you're using Doom Emacs, I think there is some lazy loading of tool bar configuration that I haven't been able to get to the bottom of yet. So if you just put `(tool-bar-mode 0)` in your Doom's `config.el` file, it doesn't fix the issue, but if you explicitly toggle `tool-bar-mode` off after (Doom) Emacs has started up, you'll get the much smaller title bar.

**Comment by dpassen** [comment]
Looks like this may have been fixed upstream https://bitbucket.org/mituharu/emacs-mac/commits/5f6c306095c825eb01708e336f9d03c15271dfe9
