### ISSUE TITLE
Libgccjit failing to compile

### ISSUE THREAD

**Issue by lebenna** [railwaycat/homebrew-emacsmacport#378]
Exact same issue as #331

**Comment by nepomucen-s** [comment]
Looks like this is a problem with the homebrew upstream libgccjit formula. Check out this [link](https://github.com/daviderestivo/homebrew-emacs-head/issues/206). This helped me on the fresh Sonoma 14.4.1 installation.

`ln -s /usr/local/Cellar/libgccjit/14.1.0/lib/gcc/14/libgccjit.dylib /usr/local/lib/
ln -s /usr/local/Cellar/libgccjit/14.1.0/lib/gcc/14/libgccjit.0.dylib /usr/local/lib/

ln -s /usr/local/Cellar/gcc/14.1.0/lib/gcc/14/libgcc_s.1.dylib /usr/local/lib/
ln -s /usr/local/Cellar/gcc/14.1.0/lib/gcc/14/libgcc_s.1.1.dylib /usr/local/lib/`

**Comment by adamliter** [comment]
[Seems to be an upstream issue in Homebrew because of the old Homebrew path for Intel-based CPUs](https://github.com/daviderestivo/homebrew-emacs-head/issues/206#issuecomment-2118742269).

**Comment by tbdcit** [comment]
Having the same problem and manually linking the libraries as suggested above has not worked for me.

**Comment by stormwatch** [comment]
> Having the same problem and manually linking the libraries as suggested above has not worked for me.

It worked for me.

**Comment by adamliter** [comment]
This should be resolved as of https://github.com/Homebrew/homebrew-core/pull/171811. You should be able to do `brew update && brew reinstall libgccjit` to fix the problem.
