### ISSUE TITLE
failed to clone official repo

### ISSUE THREAD

**Issue by bixuanzju** [railwaycat/homebrew-emacsmacport#38]
`brew install emacs-mac --with-official-repo` would give

> ==> Installing emacs-mac from railwaycat/homebrew-emacsmacport
> ==> Cloning http://www.math.s.chiba-u.ac.jp/~mituharu/emacs-mac.git
> Updating /Library/Caches/Homebrew/emacs-mac--git
> fatal: dumb http transport does not support --depth

**Comment by 11Kilobytes** [comment]
I would like to draw attention to this issue.

**Comment by railwaycat** [comment]
People complained official repo quite a bit when script first included it, that's the reason https://github.com/railwaycat/mirror-emacs-mac still existing...

In the recent mails Mr. Yamamoto seems moving his repo to Bitbucket, let's see how it works when he release next version of mac port.

**Comment by railwaycat** [comment]
After Mr. Yamamoto moved his working repo to BitBucket, this issue no longer exists. mirror-emacs-mac also retired.
