### ISSUE TITLE
Error: /Library/Caches/Homebrew/Formula/emacs-mac.rb:4

### ISSUE THREAD

**Issue by incandescentman** [railwaycat/homebrew-emacsmacport#39]
I ran `$ brew install https://github.com/railwaycat/homebrew-emacsmacport/blob/master/Formula/emacs-mac.rb` and got this error: 

Error: /Library/Caches/Homebrew/Formula/emacs-mac.rb:4: syntax error, unexpected '<'
<!DOCTYPE html>
 ^
/Library/Caches/Homebrew/Formula/emacs-mac.rb:5: syntax error, unexpected '<'
<html lang="en" class="">
 ^
/Library/Caches/Homebrew/Formula/emacs-mac.rb:5: syntax error, unexpected keyword_class, expecting end-of-input
<html lang="en" class="">
                     ^
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:22:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:22:in`load_formula'
/usr/local/Library/Homebrew/formulary.rb:79:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:134:in`load_file'
/usr/local/Library/Homebrew/formulary.rb:70:in `klass'
/usr/local/Library/Homebrew/formulary.rb:66:in`get_formula'
/usr/local/Library/Homebrew/formulary.rb:176:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:18:in`block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in`formulae'
/usr/local/Library/Homebrew/cmd/install.rb:45:in `install'
/usr/local/Library/brew.rb:127:in`<main>'

**Comment by railwaycat** [comment]
Hi, I think you need to use this address `https://raw.githubusercontent.com/railwaycat/homebrew-emacsmacport/master/Formula/emacs-mac.rb` for formula instead of the html webpage?

**Comment by incandescentman** [comment]
Thanks! Will that formula continue to be updated with the most recent build even though this repository is retired? Also, is it the same as running `brew install emacs-mac`?

**Comment by railwaycat** [comment]
Sorry for the reply after years. Yes, scripts are updated through the years.
