### ISSUE TITLE
emacsclient -nw not creating a frame in terminal

### ISSUE THREAD

**Issue by ygt-davidstirling** [railwaycat/homebrew-emacsmacport#41]
The `-nw` (or `-t`, `--tty`) should "open a new Emacs frame on the current terminal", however it actually has the same effect as `-c` in creating another graphical frame.

This is preventing me from connecting to my Emacs server via SSH. I'm using emacs-24.5-mac-5.10.

**Comment by fatlazycat** [comment]
Same here

**Comment by andrebeat** [comment]
It isn't supported. https://github.com/railwaycat/mirror-emacs-mac/blob/master/README-mac#L212

**Comment by ygt-davidstirling** [comment]
Thanks for the info @andrebeat I ended up using [Emacs For Mac OS X](http://emacsformacosx.com/) where the developers do know how to implement multi-tty with GUI.
