### ISSUE TITLE
Clang compilation errors

### ISSUE THREAD

**Issue by dhaley** [railwaycat/homebrew-emacsmacport#42]
I'm getting these complication errors on OS X 10.10.5 when running `brew upgrade emacs-mac`.

==> ./configure --prefix=/usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.11 --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-mac/emacs-24.5-z

==> make
Last 15 lines from /Users/dhaley/Library/Logs/Homebrew/emacs-mac/03.make:
1 error generated.
make[1]: **\* [scroll.o] Error 1
1 error generated.
1 error generated.
make[1]: **\* [xmenu.o] Error 1
make[1]: **\* [menu.o] Error 1
1 error generated.
make[1]: **\* [frame.o] Error 1
1 error generated.
make[1]: **\* [dispnew.o] Error 1
1 error generated.
make[1]: **\* [window.o] Error 1
1 error generated.
make[1]: **\* [xdisp.o] Error 1
make: **\* [src] Error 2

Any ideas on how I should debug?  Thanks.

**Comment by railwaycat** [comment]
Sorry, I will close this issue for now. Please feel free to reopen it or open a new issue if you see this problem again. Thanks!
