### ISSUE TITLE
"FairPlay decryption failed on binary" when running built app bundle

### ISSUE THREAD

**Issue by jonathanj** [railwaycat/homebrew-emacsmacport#43]
When building `emacs-24.5-z-mac-5.13` on OS X 10.11.1 (following the installation instructions in the README) it produces an app bundle that refuses to open when running it from Finder. `open -a /usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.13/Emacs.app` seems to work (the app runs, at least).

Looking in Console.app I see entries like these for every attempt to start it via Finder:

```
2015/11/05 08:56:37,032 com.apple.xpc.launchd[1]: (org.gnu.Emacs.199712[89445]) FairPlay decryption failed on binary.
```

I don't recall having this issue with 5.11 and I think I built that on the same version of OS X but I can't be sure (and I don't have the app bundle anymore to check.)

Prebuilt binaries from the releases page here seem to be okay.

Some googling for this error turns up a few results where a shell script in an app bundle fails to execute under launchd (for reasons unknown) and results in this same situation, I'm not sure if this is relevant or not.

**Comment by liukun** [comment]
Met the same problem. The prebuilt emacs-24.5-mac-5.13-spacemacs-icon not works either.

**Comment by napopa** [comment]
Same here on 10.11.1. Prebuilt binaries don't work either.. I went back to 5.11 for now

**Comment by crmne** [comment]
see also railwaycat/emacs-mac-port#84

**Comment by railwaycat** [comment]
Sorry for the issue!

FYI, I had a update on railwaycat/emacs-mac-port#84 side.
