### ISSUE TITLE
emacs-24.5-z-mac-5.13 does not start normally

### ISSUE THREAD

**Issue by chuchana** [railwaycat/homebrew-emacsmacport#44]
Since the last update (emacs-24.5-z-mac-5.13) I have to run `open /Applications/Emacs.app` in a terminal to open Emacs. 

I cannot open it by double-clicking or via a launcher.

I can get it to the foreground by double-clicking or via a launcher once it is running.

**Comment by scooby** [comment]
Same issue, though I've been seeing it since 5.10. Flipping through the logs in Console doesn't show any errors being thrown. xattr doesn't show any quarantine set, or any attributes set.

**Comment by chuchana** [comment]
I am not sure which version I had before, but I had skipped at least one.

**Comment by scooby** [comment]
Probably also worth noting that I'm on OS X 10.10.5, and also tried renaming my .emacs.d directory, no apparent errors.

**Comment by napopa** [comment]
This is probably the same error reported here 

https://github.com/railwaycat/emacs-mac-port/issues/84

**Comment by chuchana** [comment]
@napopa Right. I had not seen that one.

**Comment by railwaycat** [comment]
Sorry for the bug:( Could you take a look at Console.app to see if you can see this log mentioned in #43 if issue still there? Will very appreciate for that! 

`(org.gnu.Emacs.199712[89445]) FairPlay decryption failed on binary.` (PID numbers may vary)

**Comment by chuchana** [comment]
Yes: `(org.gnu.Emacs.35552[41368]) FairPlay decryption failed on binary.`

Searching for that error, I found [this](https://discussions.apple.com/thread/7278718?start=0&tstart=0) which helped me solve the problem. I just had to copy the content from `Emacs.app/Contents/MacOS/Emacs.sh` into a new file with the same name.

Thank you!

**Comment by napopa** [comment]
@chuchana I was having the same problem on 5.14 and your suggestion worked... Thanks!

**Comment by chuchana** [comment]
Looks like 5.15 fixed this problem.
