### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by sandinmyjoints** [railwaycat/homebrew-emacsmacport#47]
I'd love to know what changes are in each new release. The old repo had that information iirc, but I can't find it in this one. Am I missing it? Or if it is available somewhere else, could you link to it?

**Comment by geodenx** [comment]
The Formula of homebrew-emacsmacport utilizes mirror-emacs-mac repo.
You can find the commit log here:
https://github.com/railwaycat/mirror-emacs-mac/commits/master

**Comment by sandinmyjoints** [comment]
Cool, thanks!
