### ISSUE TITLE
Does emacs-24.5-mac-5.15 (or 5.14) build work on Mavericks ? (10.9.5)

### ISSUE THREAD

**Issue by jfbu** [railwaycat/homebrew-emacsmacport#49]
The Emacs.app from emacs-24.5-mac-5.15 or 5.14 refuse to open on my MBA under Mavericks 10.9.5.

I tried control-click in the FInder on the Emacs from Applications window but it refuses to launch (system localized to French, message says to check if app is compatible with system).

In the past I proceeded the same way and had no issue.

Any advice ?

**Comment by railwaycat** [comment]
Yes, 5.14 and 5.15 building on 10.10.5.

It's because of this issue #44 and I tried to narrow down to found the mystery root cause, which includes building on 10.10(instead of 10.9) and stop sign bundle with my developer key. 

It looks #44 more likely an upstream bug and I glad to know there still 10.9 users:)

I can put the bundle building script (from [old repo](https://github.com/railwaycat/emacs-mac-port) with slightly change) to gist to build your own if you needed it immediately; and later upload a "for 10.9.*" version to release.

And if you are an Homebrew user then it's still safe if you install by `brew`.

**Comment by railwaycat** [comment]
building script: https://gist.github.com/railwaycat/10988446

**Comment by jfbu** [comment]
I am not an advanced user and there is no urgent need for me to get 5.14 or 5.15 to work on my 10.9.5; but thanks for the building script and I will give a try tomorrow on Mavericks.

Good to know that you may again build on 10.9 in the future.

I can report regarding #44 that I had no such issue as reported there using 5.13 on 10.9.5.

Thanks for your work !

**Comment by jfbu** [comment]
I have given a try to the building script, I got some issues:

1. I had to manually add --host, --build, --target to the ./configure line in the script. I chose `--build="x86_64-apple-darwin13.4.0" --host="x86_64-apple-darwin13.4.0" --target="x86_64"` although perhaps it is not the good thing (I have no experience). But then compilation launched.

2. the build stopped with 

```
./build-aux/move-if-change ${tempfile} ./info/dir
Specify destination file
mv: rename info-dir.29512 to ./info/dir: No such file or directory
Makefile:1005: recipe for target 'info/dir' failed
make[1]: *** [info/dir] Error 1
make[1]: Leaving directory '/Users/xxxxxxxxxxxxxx/TEMP-emacs-build/mirror-emacs-mac'
Makefile:1073: recipe for target 'info' failed
make: *** [info] Error 2
```
but I did find `Emacs.app` and it does appear to work

```
GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, Carbon Version 157 AppKit 1265.21)
 of 2015-12-21 on Anonymous.local
```
I have not tested it though. (`M-x info` does seem to work also at least partially).

Last remark: the build script is dangerous if the user forgets to pass it a repertory name as argument; with no argument the `cd $1` then `find . -name *.elc | xargs rm` will remove all `.elc` files in user repertory ...

**Comment by jfbu** [comment]
Hi release https://github.com/railwaycat/homebrew-emacsmacport/releases/tag/emacs-24.5-mac-5.16 launches successfully on Mavericks too (10.9.5), thanks! :+1:
