### ISSUE TITLE
Yomamoto Mituharu has begun pushing to bitbucket

### ISSUE THREAD

**Issue by gordonmcshane** [railwaycat/homebrew-emacsmacport#53]
Just letting you know, @railwaycat 
https://bitbucket.org/mituharu/emacs-mac/overview

**Comment by railwaycat** [comment]
There's quite big change of the relation between mac port and emacs 25 branch. Part of mac port code already in 25 branch, and it's not very clear if the rest will in or not. 

I'm waiting for the next release announcement from Mr. Yamamoto to see in which way he is going to release mac port from 25.

**Comment by gordonmcshane** [comment]
Did emacs end up merging his port into master?

**Comment by railwaycat** [comment]
I think the answer is 'no'...

**Comment by railwaycat** [comment]
Now `--HEAD` will install pretest `25.1` version from Bitbucket "work" branch.

**Comment by railwaycat** [comment]
Now `--HEAD` is 26.0.90 pretest. I close this issue for now.
