### ISSUE TITLE
key sequence cannot be used

### ISSUE THREAD

**Issue by cmal** [railwaycat/homebrew-emacsmacport#54]
C-/
C-<
C->
When pressing these key sequences, there is not any response.
Can your Emacs read these keymaps correctly?

**Comment by railwaycat** [comment]
At least it works for me:

C-/

```
C-/ runs the command undo, which is an interactive compiled Lisp function in
`simple.el'.

It is bound to C-_, H-z, <undo>, C-/, C-x u, <menu-bar> <edit> <undo>.

(undo &optional ARG)
```

C-< and C-> not defined by default, but they are both able to caught by C-h k.

Maybe something in your configuration file? Have a try with running `/Applications/Emacs.app/Contents/MacOS/Emacs -q`, which will avoid all configs.

**Comment by panjie** [comment]
C-/ not works for me too. 

Environment:
* OS: 10.13
* Emacs: GNU Emacs 25.3.1 (x86_64-apple-darwin16.7.0, Carbon Version 157 AppKit 1504.83) of 2017-09-17

**Comment by songsanli** [comment]
<kbd>C-/</kbd>, <kbd>C-=</kbd>, <kbd>C-<</kbd>, <kbd>C-></kbd> don't work for me either.

I've test above keys in `/Applications/Emacs.app/Contents/MacOS/Emacs -Q` by `describe-key` command.

Environment:
- OS: 10.13.3
- Emacs: GNU Emacs 26.0.91 (build 1, x86_64-apple-darwin17.4.0, Carbon Version 158 AppKit 1561.2)
 of 2018-02-26

**Comment by railwaycat** [comment]
Hi @songsanli, could you please publish the output from `describe-key`? For the key sequences you mentioned.

**Comment by railwaycat** [comment]
Also, is the input method on (I mean at languages other than English)?

**Comment by songsanli** [comment]
@railwaycat Thx for reply :thumbsup:

Those key sequences **work** again after I change me input method to English :joy:

**Comment by songsanli** [comment]
@railwaycat However, in official Emacs mac version, I can use those key sequence even if in Chinese input method.

Back to emacs-mac. When in Chinese input method (macOS standard), no output from `describe-key` when I press above keys. It just like I didn't key anything.

**Comment by railwaycat** [comment]
@songsanli Great! Looks more like a Mac-port bug..It would be great if you could report this bug to the developer by this email address: mituharu+bug-gnu-emacs-mac@math.s.chiba-u.ac.jp

**Comment by songsanli** [comment]
@railwaycat I've contacted with Mituharu and he gives me a workaround:

```lisp
(setq mac-pass-control-to-system nil)
```

It **works** for me. But he also warned me that this config would intercept all the keys with the control modifier. I guess it may cause failure of system shortcuts related to <kbd>ctrl</kbd> in Emacs (I don't run into any problem yet) and I'll reply to him to get more accurate info.
