### ISSUE TITLE
`M-h` is swallowed by OS X

### ISSUE THREAD

**Issue by stig** [railwaycat/homebrew-emacsmacport#55]
I recently started using this port over the default brew one. I love the improved fonts, and speed. However, this port has a problem in that `M-h` is swallowed by OS X. Is there any way to unbind that, so that it goes back to being handled by Emacs?

**Comment by railwaycat** [comment]
This one may help you: https://github.com/railwaycat/emacs-mac-port/issues/78

**Comment by stig** [comment]
Yep! That did the trick. Thank you!

**Comment by zzp0** [comment]
What about `Command-Control-D` for looking up a word?  Is there any way to disable it?

**Comment by sooheon** [comment]
It looks like the above, and `Command-space` to switch input source can't be disabled.

**Comment by DarwinAwardWinner** [comment]
The link above is dead. Is there a new place I can find a fix for this?

**Comment by railwaycat** [comment]
Sorry, I set the old repo to private to reduce the confusing with the official Bitbucket git repository. 

The setting mentioned in the link is:

`(setq mac-pass-command-to-system nil)`

This suggestion is from @incandescentman.
