### ISSUE TITLE
Permission issues?

### ISSUE THREAD

**Issue by nedludd** [railwaycat/homebrew-emacsmacport#56]
When I try to delete a file or directory I get what seems to be a permission error:

`(file-error Removing old name Mac error -600 /Users/johndoe/tmp/foo)`

"Debug on Error" is not activated by this issue.

I can create files or directories in dired but cannot delete them.  It's not limited to dired though, as when "package.el" updates packages it cannot delete the old directories.

It does not happen with stock emacs (from Homebrew).

**Comment by llelf** [comment]
I've had the same issue;  I have `mac-system-move-file-to-trash-use-finder` set to `t`.
As I soon found out,  the reason for the error is simple — no Finder running.  It works fine the moment I start it.

Would it be hard to activate/start it (“window-less”) first?

**Comment by railwaycat** [comment]
Close the issue for now, since the permission management of macOS changed a lot. Also this repo is only for the formula and packing of Homebrew, it won't and can't modify the upstream.
