### ISSUE TITLE
Add support for custom icons

### ISSUE THREAD

**Issue by jiri** [railwaycat/homebrew-emacsmacport#57]
having `--with-custom-icon=URL` would not only enable people like me to use custom icons without having to replace them after every update, but also remove the need for several icon options that are present currently. Any custom emacs distribution (like Spacemacs) could just provide an URL to an icon, which would enable them to change it independently of this formula.

**Comment by railwaycat** [comment]
That's a good idea, thanks!

And just let you know if you install by home-brew script it has built-in Spacemacs icon.

**Comment by jiri** [comment]
Yeah, I know the Spacemacs one is built-in, the point I was trying to make was that this options would let us remove the Spacemacs icon and modern icon options in favour of a more general one, perhaps supplying shorthands for the common ones, like:
 - `--with-custom-icon=URL`
 - `--with-custom-icon=spacemacs`

**Comment by jiri** [comment]
Note that this would also solve #45 :octocat:

**Comment by avelino** [comment]
do not like the idea, dynamic URL (open field) can generate some errors and does not guarantee integrity

**Comment by railwaycat** [comment]
As far as I know Homebrew does not allow a formula to accept a string from option. Options are only binary and fixed. There is not anything this formula can do unless we see changes from Homebrew.
