### ISSUE TITLE
Error: undefined local variable or method `emacs_icons_project_icons

### ISSUE THREAD

**Issue by igrejas** [railwaycat/homebrew-emacsmacport#61]
I run $brew install emacs-mac and I get this error

What am I doing wrong

Error: undefined local variable or method `emacs_icons_project_icons' for #<Formulary::FormulaNamespacebd11bbab2e923a67956ab0b7e84d11cd::EmacsMac:0x007fa812a42c90>
Please report this bug:
    https://git.io/brew-troubleshooting
/Library/Caches/Homebrew/Formula/emacs-mac.rb:107:in`install'
/usr/local/Library/Homebrew/build.rb:130:in `block in install'
/usr/local/Library/Homebrew/formula.rb:930:in`block in brew'
/usr/local/Library/Homebrew/formula.rb:1550:in `block in stage'
/usr/local/Library/Homebrew/resource.rb:92:in`block in unpack'
/usr/local/Library/Homebrew/extend/fileutils.rb:37:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:88:in`unpack'
/usr/local/Library/Homebrew/resource.rb:81:in `stage'
/usr/local/Library/Homebrew/formula.rb:1540:in`stage'
/usr/local/Library/Homebrew/formula.rb:926:in `brew'
/usr/local/Library/Homebrew/build.rb:108:in`install'
/usr/local/Library/Homebrew/build.rb:177:in `<main>'

**Comment by railwaycat** [comment]
Sorry about that! A mistake in the previous merge.

Should fixed after commit https://github.com/railwaycat/homebrew-emacsmacport/commit/26dac4b2749cccac429fe916448b0c411a1edf32

**Comment by igrejas** [comment]
Sorry, but I'm still getting the same error.

**Comment by igrejas** [comment]
Fixed. Thanks.
