### ISSUE TITLE
missing ns-copy-including-secondary function in ns-win.el

### ISSUE THREAD

**Issue by GHpku** [railwaycat/homebrew-emacsmacport#63]
I am using the prebuilt emacs-24.5-mac-5.13 on Mavericks (10.9.5). Before that I was using emacs 24.3 that was built from source myself. In the old version of Emacs, I found that S-c and S-v did the copy and paste job very well as in other apps on OS X. When I switched to the more recent one, I found these keystrokes are undefined. I tried to bind them to functions in a consistent way with the old emacs, but I found ns-copy-including-secondary seems not working, though I can find it in ns-win.el. Any idea on this issue?

**Comment by railwaycat** [comment]
Hi @GHpku , `ns-*` functions are valid only for nextstep port (the official one), instead, you can use `kill-ring-save` which talks with OS X system clipboard under mac port. 

You could use `(eq window-system 'mac)` and `(eq window-system 'ns)` to adjust you configuration for mac port and nextstep port.

**Comment by GHpku** [comment]
Thanks for the prompt reply. I'll give a try. Consider it closed then.
