### ISSUE TITLE
lack of --with-librsvg flag

### ISSUE THREAD

**Issue by sooheon** [railwaycat/homebrew-emacsmacport#66]
Is this a deliberate deviation from the homebrew `emacs` package by Yamamoto? The colors look washed out, and a little googling points to this being the culprit.

**Comment by railwaycat** [comment]
Emacs mac port do SVG image display via Webkit framework, there's no need for librsvg.

**Comment by sooheon** [comment]
Thanks. What about for sRGB? I actually meant that by "the colors," don't know why I typed svg...

**Comment by railwaycat** [comment]
sRGB enabled by default quite early before, after 10.8 as I remember - if my memory is correct...

**Comment by sooheon** [comment]
I see, thanks!
