### ISSUE TITLE
Update official icon

### ISSUE THREAD

**Issue by houli** [railwaycat/homebrew-emacsmacport#67]
Emacs 25 comes with a new set of official icons.
The icon at https://s3.amazonaws.com/emacs-mac-port/Emacs.icns should be replaced with an icns based off the following svg https://bitbucket.org/mituharu/emacs-mac/src/f3402395995bf70e50d6e65f841e44d5f9b4603c/etc/images/icons/hicolor/scalable/apps/emacs.svg?at=master&fileviewer=file-view-default

Also in the source repository the default icon at `mac/Emacs.app/Content/Resources/Emacs.icns` should also probably be replaced with this new icon.

**Comment by railwaycat** [comment]
Thanks to point it out!

I have updated the link in brew formula for new official icon, could you try it again?

**Comment by houli** [comment]
Yes this is working as expected. Thank you for updating the icon.

Is there a reason why [this](https://bitbucket.org/mituharu/emacs-mac/src/f3402395995bf70e50d6e65f841e44d5f9b4603c/mac/Emacs.app/Contents/Resources/Emacs.icns?at=master&fileviewer=file-view-default) file in the source repository hasn't been changed to the new Emacs 25 icon?
Then we wouldn't need to pass any flags to get the official Emacs icon.

**Comment by houli** [comment]
Ah excuse me, I see you are not the maintainer of the port. I will send them an email asking them to incorporate the new icns you made. Thanks!

**Comment by railwaycat** [comment]
@houli Not a problem :) I think it might because of this icon been used all the way even from the earliest carbon port, it never changed.
