### ISSUE TITLE
Fullscreen on emacs-25.1-rc1-mac-5.90

### ISSUE THREAD

**Issue by fatlazycat** [railwaycat/homebrew-emacsmacport#68]
Fullscreen on launch with spacemacs doesn't create the correct fullscreen 'mode'

The dock appears when mouse goes near the appropriate area. And switching spaces is obviously incorrect.

It's just maximised, if I toggle 'fullscreen' with ctrl, cmf & f twice then it is correct.

**Comment by angrybacon** [comment]
This behavior is exactly why I use this build.

**Comment by neglectedvalue** [comment]
The same problem on `emacs-25.2-z-mac-6.3`
http://take.ms/NIB4r
The dock disappears after entering into Mission Control.
It is really annoying because Dock overlaps the mode-lines.

**Comment by LdBeth** [comment]
> Being a port of Emacs 25, the Mac port also supports the following
Emacs 23 features besides those inherited from the above ancestors:
>  * The `fullscreen' frame parameter, with all values supported:
    `fullboth', `fullwidth', `fullheight', and `maximized'.  The
    fullboth frames, which don't have the title bar, still allow us to
    access the menu bar, the Dock, and the tool bars.  The menu bar
    can also be activated via `menu-bar-open', `Control-F2' (if full
    keyboard access enabled), or `Command-Shift-/' (on Mac OS X 10.5
    and later) even for fullboth frames where the menu bar is usually
    hidden.  Changing fonts or internal-border-width in fullscreen
    frames does not clutter display.  On multiple monitor
    environments, one can move fullscreen frames to another monitor by
    setting the `left' and `top' frame parameters accordingly.
    Attaching/detaching external monitors should work even with
    fullscreen frames.

It is actually a feature. See the [descriptions on official project page](https://bitbucket.org/mituharu/emacs-mac).

**Comment by neglectedvalue** [comment]
@LdBeth And according to the description it doesn't say that Dock has to be always shown on top of Emacs. Otherwise, it hides informative parts of mode-lines, and as a user, I would not expect it.

**Comment by railwaycat** [comment]
This repo is for Homebrew formula and packing only. Possible changes to upstream is out of scope. I will close the issue for now.
