### ISSUE TITLE
Cannot scale SVG previews

### ISSUE THREAD

**Issue by adam52** [railwaycat/homebrew-emacsmacport#69]
Inline previews of SVGs fail if you attempt to re-scale them in an org-mode buffer. for example:

```
#+ATTR_ORG: :width 200
[[./randomImage.svg]]
```

The width tag works just fine with all other image types. And SVGs will display if the tag is removed...?

**Comment by railwaycat** [comment]
Sorry I will close this issue because of the age. You are welcome to open a new one if this issue still consistent on the latest version.
