### ISSUE TITLE
Dependency tweaks

### ISSUE THREAD

**Issue by DomT4** [railwaycat/homebrew-emacsmacport#70]
Would you mind changing:
```ruby
depends_on :autoconf => :build
depends_on :automake => :build
```
to:
```ruby
depends_on "autoconf" => :build
depends_on "automake" => :build
```
in [your formula](https://github.com/railwaycat/homebrew-emacsmacport/blob/master/Formula/emacs-mac.rb)?

We deprecated the symbol versions of those dependencies a fair while ago, but have recently tightened up enforcement. You should be able to discover these things in future by periodically running a `brew audit` on the formula. Thanks!

**Comment by railwaycat** [comment]
Thanks @DomT4, I just committed 0a0f78d to fix this issue. 

And thanks again for your suggestion of `brew audit` :)

**Comment by DomT4** [comment]
Thank you @railwaycat, appreciate the quick fix! 😃
