### ISSUE TITLE
Installing latest org through elpa results in latex fragment preview feature regression

### ISSUE THREAD

**Issue by sooheon** [railwaycat/homebrew-emacsmacport#73]
With the latest emacs-mac build (25.1.1), the org-version which comes bundled (8.2.10) is not the latest (8.3.5). When I manually update to 8.3.5 using org through elpa, I lose the high resolution latex snippet previews that existed previously. Is this because the high resolution stuff is manually patched? Do I simply have to wait for a higher version org to come bundled with emacs-mac?

**Comment by railwaycat** [comment]
Sorry I will close this issue because of the age. You are welcome to open a new one if this issue still consistent on the latest version.
