### ISSUE TITLE
Scroll performance issue

### ISSUE THREAD

**Issue by angrybacon** [railwaycat/homebrew-emacsmacport#74]
I always had serious issues with the smooth scrolling. I recently tried another build (emacsformacosx) and the smooth scroll was very much "smoother", even with `-Q`.

I tried that other build with:

``` elisp
(use-package mwheel
  :config
  (setq-default
   mouse-wheel-scroll-amount '(1 ((shift) 2) ((control) . nil))
   mouse-wheel-progressive-speed nil))

(use-package smooth-scrolling
  :init (smooth-scrolling-mode 1)
  :config (setq-default smooth-scroll-margin 1))
```

However, that scroll doesn't feel natural as opposed as with your build (fading speed).

**Comment by jesuspc** [comment]
👍  Also having issues here. That's being reported by the profiler:

   - mac-mwheel-scroll                                  6,503,476,505  86%
    + #<compiled 0x55cf7f01>                            1,208,175,142  16%
    + redisplay                                           970,620,372  12%
    +  count-screen-lines                                  573,393,776   7%
    + pos-visible-in-window-p                               1,221,260   0%
    + window-inside-pixel-edges                               870,160   0%
    + window-end                                              813,524   0%
    + scroll-down                                             645,948   0%
    + scroll-up                                               469,000   0%
    + select-window                                           408,948   0%

**Comment by cmpis** [comment]
I'm not sure if I'm seeing the same issue, but after updating to Emacs 25 I've been seeing performance issues with scrolling. The screen doesn't really refresh while I'm scrolling in some buffers.

**Comment by arnemart** [comment]
I'm having serious scrolling performance issues as well. The pixel-by-pixel scrolling is so choppy as to be mostly unusable, often less than 1 fps. But when I disable `mac-mouse-wheel-smooth-scroll`, momentum scrolling disappears altogether, and I do not know how to get it back. In other emacs builds (e.g. emacsformacosx as mentioned above) momentum scrolling works and sends scroll events as expected.

Is it possible to get momentum scrolling to work without enabling pixel-by-pixel scrolling? Or is there perhaps a way to get the pixel scrolling to perform adequately?

**Comment by railwaycat** [comment]
This repo is for Homebrew formula and packing only. Possible changes to upstream is out of scope. 

As far as I can see, scroll performance has improved since this issue be opened. Also the official stream(ns port) of emacs 29 introduced implement of a smooth scroll feature for all platforms.
