### ISSUE TITLE
Fails to Install on El Capitan

### ISSUE THREAD

**Issue by timuckun** [railwaycat/homebrew-emacsmacport#75]
==> Installing emacs-mac from railwaycat/emacsmacport
==> Downloading https://bitbucket.org/mituharu/emacs-mac/get/emacs-25.1-rc2-mac-5.91.tar.gz
Already downloaded: /Users/tim/Library/Caches/Homebrew/emacs-mac-emacs-25.1-rc2-mac-5.91.tar.gz
==> ./autogen.sh
==> ./configure --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-mac/emacs-25.1-rc2-mac-5.91/s
Last 15 lines from /Users/tim/Library/Logs/Homebrew/emacs-mac/02.configure:
checking for a thread-safe mkdir -p... build-aux/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make supports nested variables... (cached) yes
checking build system type... x86_64-apple-darwin15.6.0
checking host system type... x86_64-apple-darwin15.6.0
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/private/tmp/emacs-mac-20160829-25184-9dpwxb/mituharu-emacs-mac-990dafce23a6':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/railwaycat/homebrew-emacsmacport/issues

These open issues may also help:
Fullscreen on emacs-25.1-rc1-mac-5.90 https://github.com/railwaycat/homebrew-emacsmacport/issues/68
Error: /Library/Caches/Homebrew/Formula/emacs-mac.rb:4 https://github.com/railwaycat/homebrew-emacsmacport/issues/39
emacs-mac failed to build on 10.10.2 https://github.com/railwaycat/homebrew-emacsmacport/issues/17
Does emacs-24.5-mac-5.15 (or 5.14) build work on Mavericks ? (10.9.5) https://github.com/railwaycat/homebrew-emacsmacport/issues/4

**Comment by railwaycat** [comment]
Hi @timuckun, could you post your `brew config` and `xcode-select -p`? Thanks!

I would suspect it's a compiler/SDK config issue.

**Comment by timuckun** [comment]
brew config
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: b9d5b11f321a359b462aa2c353c2bdb483930fb3
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b163b0d8271500557664422d6fdc3054d0ff7d31
Core tap last commit: 3 weeks ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
GCC-4.2: build 5666
Clang: 6.1 build 602
Git: 2.2.1 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Users/tim/.rubies/ruby-2.3.1/bin/ruby
Java: 1.8.0_25, 1.7.0_45
OS X: 10.11.6-x86_64
Xcode: 6.4
CLT: N/A
X11: N/A



xcode-select -p
/Applications/Xcode.app/Contents/Developer

**Comment by railwaycat** [comment]
If there's no specific reason, I would suggest you to do 

1. Upgrade Xcode to the latest 7.3.1 
2. Install Command line tools by `xcode-select --install`

**Comment by timuckun** [comment]
Upgrading xcode worked.

Thanks.
