### ISSUE TITLE
Add support for building with xwidgets

### ISSUE THREAD

**Issue by AriaFallah** [railwaycat/homebrew-emacsmacport#79]
Trying to use xwidgets gives the error

```
Your emacs was not compiled with xwidgets support
```

**Comment by railwaycat** [comment]
Yes, xwidgets support is gtk only.

**Comment by railwaycat** [comment]
FYI: http://lists.gnu.org/archive/html/emacs-devel/2016-10/msg00255.html

Looks like there's no plan to support xwidgets on macOS for mac port or nextstep port.

**Comment by AriaFallah** [comment]
@railwaycat ah ok good to know thanks!

**Comment by vikasrawal** [comment]
Would this not suffice?

http://brewformulas.org/Gtk+

**Comment by jackrusher** [comment]
Hi! :) It appears that other MacOS emacs builds can now support xwidget-webkit natively: 
https://jft.home.blog/2020/01/24/a-browser-in-your-emacs-macos/
... so I wanted to raise the possibility of reopening this issue.

**Comment by railwaycat** [comment]
Hi @jackrusher, if I understand the blog correctly the `xwidget-webkit` option is on 28/head and need Cocoa(NS port) support. The develop Emacs mac port branch still on 27. I don't know about the roadmap but let's see if mac port is going to add the feature when it move to 28 in the future.

**Comment by ymfsing** [comment]
Hi @railwaycat , there is a patch [xwidgets_webkit_in_cocoa.patch](https://github.com/d12frosted/homebrew-emacs-plus/blob/master/patches/emacs-27/xwidgets_webkit_in_cocoa.patch)  I find from emacs-plus [xwidgets](https://github.com/d12frosted/homebrew-emacs-plus#xwidgets-webkit).

**Comment by kommen** [comment]
FWIW: I experimented by taking the xwidgets_webkit_in_cocoa.patch from emacs-plus 27.1 and hacking it to make it work with the emacs-mac port by just substituting all occurrences of `NS_IMPL_COCOA` with `HAVE_MACGUI`, but the result didn't compile with compiler errors in `nsxwidget`.
