### ISSUE TITLE
emacsclient won't open a new frame

### ISSUE THREAD

**Issue by benmaughan** [railwaycat/homebrew-emacsmacport#82]
First, thanks for this great project! 

If I start the emacs daemon with

/usr/local/Cellar/emacs-mac/emacs-25.1-z-mac-6.0/bin/emacs -Q --daemon

and then start a client with

/usr/local/Cellar/emacs-mac/emacs-25.1-z-mac-6.0/bin/emacsclient -c

then the client starts in the terminal, and not in a new GUI frame as expected (i.e. as if I had used the -t option). 

I'm using the latest homebrew build (25.1.1) on OS X 10.10.5 and also see this behaviour if I use the emacsport binary build. If I use emacsformacosx then I see the normal desired behaviour.

**Comment by railwaycat** [comment]
Hi @benmaughan, I would like to forward the thanks to the developer of mac port: https://bitbucket.org/mituharu/emacs-mac :)

For the issue of `emacsclient` not able to attach to GUI frame, this is a statement for multi-tty from`README-mac`
> The Mac port doesn't support multi-tty with GUI.  The developer has no
idea how to detach Emacs as a GUI application from Window Server or
Dock without separating a GUI process (not thread) from the main Emacs
(Lisp evaluator) process.  TTY-only multi-tty is supposed to work.

The official Emacs nextstep port, supports multi-tty feature.

**Comment by benmaughan** [comment]
Thanks for clarifying this for me.
