### ISSUE TITLE
The menubar of this port can not be disabled ?

### ISSUE THREAD

**Issue by Yevgnen** [railwaycat/homebrew-emacsmacport#83]
Or better to say `menu-bar-mode` has been disabled, but the menu is still there. Is this a feature or bug ? Thanks !

Running on `GNU Emacs 25.1.1 (x86_64-apple-darwin16.0.0, Carbon Version 157 AppKit 1504) of 2016-09-21` and `macOS 10.12`.

**Comment by lagooned** [comment]
It seems like it doesn't really matter if you disable the menubar or not, it will never show in the actual frame itself.

Also as a weird side effect of disabling the menubar on this build, is that you also disable the osx zoom-to-fullscreen option. I'm not sure if this is intended or not.

**Comment by Yevgnen** [comment]
@lagooned The menubar contains too many items that even hide some the widgets of the macOS global menu.

<img width="1280" alt="screen shot 2016-10-25 at 8 11 09 am" src="https://cloud.githubusercontent.com/assets/16749790/19668464/a4939c00-9a8a-11e6-8a66-0f1747f1e8d6.png">

**Comment by aiba** [comment]
Just found this issue. FWIW, I am having the same problem as @Yevgnen -- so many menus that it's hiding macOS widgets.  Is there a way to disable the macos menu items?

**Comment by Gira-X** [comment]
It helps to hide the default menus like this when the menu bar is too cramped:

```elisp
(define-key global-map [menu-bar options] nil)
(define-key global-map [menu-bar file] nil)
(define-key global-map [menu-bar File] nil)
(define-key global-map [menu-bar edit] nil)
(define-key global-map [menu-bar tools] nil)
(define-key global-map [menu-bar buffer] nil)
(define-key global-map [menu-bar help-menu] nil)
```

The `YASnippet` menu can be hidden via `M-x customize-option yas-use-menu`.

---

So far I have not found a reliable way to hide all menu items.
`(lookup-key global-map [menu-bar])` and `(lookup-key (current-local-map) [menu-bar])` lists menu bar items although I am not sure how to hide the returned items.

`(toggle-frame-fullscreen)` is also a good option which hides the entire menu bar.
