### ISSUE TITLE
Info-quoted face doesn't work in pre-built binaries

### ISSUE THREAD

**Issue by hmelman** [railwaycat/homebrew-emacsmacport#84]
I filed this as an emacs bug,
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=24793
and was told that the issue is that the info file was generated by texinfo 4 and that since texinfo 5 they generate curley quotes. Perhaps the pre-built binaries should use a later texinfo (they're up to 6) or Info-quoted's default value should be changed.

**Comment by railwaycat** [comment]
Thanks to point it out! Pre-built binaries are built with texinfo shipping with macOS, which stays on 4.8 might because of GPL3 license.  

I can add texinfo as build dependency to fix this for Homebrew users. For pre-builts, I will have a try to see if pre-built building with texinfo 6 not break on macOS with only shipping texinfo 4.8.

**Comment by railwaycat** [comment]
Er..Emacs is using the `/usr/bin/info` binary from system?

**Comment by hmelman** [comment]
I don't think so. /usr/bin/info is a reader, it's for reading manuals outside of emacs. M-x info in emacs opens a buffer in info-mode and is showing files like  /Applications/Emacs.app/Contents/Resources/info/emacs.info.gz in info-mode. Those should have been built from texinfo files at the time emacs was built. I checked that file in my emacs and it's quoting style is using ` and '.

**Comment by railwaycat** [comment]
I see...thanks!

At least as what I see Emacs building with newer version of texinfo work good on computers only have shipping texinfo 4.8

So I will add texinfo as a optional dependency for emacs-mac in Homebrew formula and make pre-built building with latest texinfo, from version 6.1.

**Comment by hmelman** [comment]
Thanks.
