### ISSUE TITLE
Instructions in readme refer to old repo name "emacsport"

### ISSUE THREAD

**Issue by gururaj-s** [railwaycat/homebrew-emacsmacport#86]
The first instruction in readme file should be corrected to read  
 
"brew tap railwaycat/homebrew-emacsmacport"

and not

"brew tap railwaycat/emacsport".

**Comment by railwaycat** [comment]
Sorry, not fully get what you meant :(

Tap name in README file is "brew tap railwaycat/emacsmacport" and Homebrew definitely able to recognize it.

**Comment by gururaj-s** [comment]
Oh - no matter then, I'll close the issue. At that time it wouldn't work
and I had to do :

"brew tap railwaycat/homebrew-emacsmacport" . No worries.

On a different note, l was trying to make my Emacs into a C++ IDE and I was
facing this strange issue with ECB (Emacs Code Browser) -  the mouse
doesn't seem to work on ECB window. It might be because of the way the Mac
port of Emacs treats mouse events - any idea if you might be able to help
me with that ?
