### ISSUE TITLE
Changning the function key to hyper

### ISSUE THREAD

**Issue by RKBK** [railwaycat/homebrew-emacsmacport#90]
I use this piece of code to change the function key to be a hyper key in the standard homebrew emacs:

```
(setq ns-function-modifier 'hyper)  ; make Fn key do Hyper
```

This variable does not appear to exist in this port. Is there an alternative command I should use?

**Comment by railwaycat** [comment]
I don't think Mac port has modifier to set function key..I know there's for option and command.

You may send email to ask developer of emacs mac port, Mr. Yamamoto<mituharu+bug-gnu-emacs-mac@math.s.chiba-u.ac.jp> for this feature.

**Comment by RKBK** [comment]
Thanks @railwaycat ! I've sent a message to professor Yamamoto.

**Comment by zzp0** [comment]
@RKBK `(setq mac-function-modifier 'hyper)`

**Comment by RKBK** [comment]
@zzp0 Thanks, that worked!
