### ISSUE TITLE
Disable macosx shortcuts

### ISSUE THREAD

**Issue by achikin** [railwaycat/homebrew-emacsmacport#98]
I mapped Cmd to Control in my emacs config. Now when I press C-h emacs window minimizes to dock. How can I disable that functionality?

**Comment by railwaycat** [comment]
I believe there's no option to control `Cmd-h` individually, but you could try this to prevent all command shortcuts to system:

```
(setq mac-pass-command-to-system nil)
```

**Comment by achikin** [comment]
This is what I was looking for, thank you!
